export type AppScreen = "app" | "settings";

export type SettingsSectionId =
  | "general"
  | "appearance"
  | "editor"
  | "shortcuts"
  | "providers"
  | "adapters"
  | "agentRoles"
  | "teams"
  | "personalization"
  | "mcp"
  | "skills"
  | "workflows"
  | "git"
  | "worktrees"
  | "about"
  | "licenses"
  | "environment"
  | "workspaces"
  | "computer"
  | "archived"
  | "diagnostics"
  | "usage";
