// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  agent: {
    activity: {
      attention: "Attention needed";
      completed: "Completed";
      planning: "Working";
      ready: "Ready";
      reasoningCount_one: "{{count}} reasoning step";
      reasoningCount_other: "{{count}} reasoning steps";
      title: "Activity";
      toolCount_one: "{{count}} tool call";
      toolCount_other: "{{count}} tool calls";
      usingTools: "Using tools";
      writing: "Responding";
    };
    assistantMessage: {
      copy: "Copy response";
      copyRichText: "Copy Rich Text";
      turnUsage: {
        ariaLabel: "Token usage this turn";
        tooltipCacheCreation: "Cache write ({{tokens}}): tokens added to the prompt cache.";
        tooltipCacheRead: "Cache read ({{tokens}}): tokens reused from the prompt cache.";
        tooltipInput: "Processed input ({{tokens}}): total input handled this turn, including cached tokens.";
        tooltipNewInput: "Uncached input ({{tokens}}): input processed without a cache hit.";
        tooltipOutput: "Output ({{tokens}}): tokens the model generated this turn.";
      };
    };
    contextBreakdown: {
      groups: {
        agents: "Agents";
        deferredTools: "Deferred tools";
        mcpTools: "MCP tools";
        memoryFiles: "Memory files";
        skills: "Skills";
        slashCommands: "Slash commands";
        systemPrompt: "System prompt";
        systemTools: "System tools";
      };
      title: "Context usage";
    };
    contextWindow: {
      cacheReadTokens: "Cache read: {{tokens}}";
      cacheWriteTokens: "Cache write: {{tokens}}";
      currentContext: "Current context";
      inputTokens: "Input: {{tokens}}";
      label: "Context window usage";
      outputTokens: "Output: {{tokens}}";
      reasoningTokens: "Reasoning: {{tokens}}";
      sessionTotals: "Session totals";
      tooltip: "{{percent}}% of context limit";
    };
    imagePreview: {
      closePreview: "Close image preview";
      copied: "Copied";
      copyFailed: "Copy failed";
      copyImage: "Copy image";
      downloadImage: "Download image";
      imagePosition: "{{current}} / {{total}}";
      nextImage: "Next image";
      previousImage: "Previous image";
      resetZoom: "Reset zoom";
      rotate: "Rotate clockwise";
      zoomIn: "Zoom in";
      zoomOut: "Zoom out";
    };
    jumpToLatest: "Jump to latest";
    jumpToTop: "Jump to top";
    navigation: {
      collapse: "Collapse navigation";
      expand: "Expand navigation";
      jumpToPrompt: "Jump to prompt {{index}}";
    };
    openFile: "Open file";
    permissions: {
      actions: {
        edit: "edit";
        read: "read";
        use: "use";
        write: "write";
      };
      allow: "Allow";
      allowOnce: "Allow once";
      allowed: "Allowed";
      alwaysAllow: "Always allow";
      claudeAction: "Allow Claude to {{action}} {{target}}?";
      command: "Command";
      denied: "Denied";
      deny: "Deny";
      files: "Files";
      path: "Path";
      pattern: "Pattern";
      pending: "Pending";
      query: "Query";
      rejectAlways: "Reject always";
      runCommand: "Run this command?";
      showLess: "Show less";
      showMore: "Show full command";
      title: "Permission request";
      url: "URL";
    };
    plan: {
      collapse: "Collapse tasks";
      dismiss: "Hide tasks";
      expand: "Expand tasks";
      label: "Tasks";
      progress: "{{done}}/{{count}}";
    };
    planApproval: {
      abandon: "Abandon plan";
      approve: "Approve and implement";
      collapse: "Show less";
      copy: "Copy plan";
      emptyHeading: "No plan written yet";
      emptySubtitle: "The agent left plan mode without writing a plan.";
      expand: "Show full plan ({{count}} lines)";
      expandMore: "Show more";
      expand_one: "";
      expand_other: "";
      feedbackDismiss: "Back";
      feedbackLabel: "What should change? Leave empty and the agent will ask.";
      feedbackPlaceholder: "e.g. keep proxy.ts untouched, only edit the README";
      feedbackSend: "Send changes";
      heading: "The agent wrote a plan";
      pending: "Waiting on you";
      requestChanges: "Request changes";
      resolvedAbandoned: "Plan abandoned";
      resolvedApproved: "Plan approved";
      resolvedCancelled: "Changes requested";
      resolvedStale: "Replaced by a newer plan";
      subtitle: "Approve it to start implementing, or send it back for changes.";
      title: "Plan approval";
      waiting: "Waiting on plan approval";
      waitingEmpty: "No plan written — approve or request changes";
    };
    previousMessage: {
      cancel: "Cancel";
      cancelEdit: "Cancel edit";
      copy: "Copy prompt";
      dialogDescription: "Submitting from a previous message will clear the messages after this one. Reverting also restores files to their checkpoint before this message.";
      dialogTitle: "Submit from a previous message?";
      dontAskAgain: "Don't ask again";
      dontRevert: "Don't revert";
      edit: "Edit previous message";
      revert: "Revert";
      revertUnavailable: "File revert is unavailable because this message has no git workspace checkpoint.";
      submitEdit: "Submit edited message";
    };
    questions: {
      answer: "Answer";
      answered: "Answered";
      pending: "Pending";
      placeholder: "Answer the question...";
      title: "Question";
    };
    queue: {
      actionFailed: "Queue action failed";
      cancel: "Cancel";
      delete: "Remove from queue";
      edit: "Edit message";
      editLabel: "Edit queued message";
      label: "Queued follow-ups";
      moreActions: "More queue actions";
      save: "Save";
      steer: "Steer";
    };
    rateLimits: {
      credits: "Usage credits";
      creditsValue: "{{used}} of {{limit}}";
      remaining: "{{percent}}% remaining";
      resets: "resets {{reset}}";
      title: "Plan usage limits";
      windows: {
        fiveHour: "5h";
        monthly: "Monthly";
        primary: "Primary";
        secondary: "Secondary";
        weekly: "Weekly";
      };
    };
    reasoning: "Reasoning";
    system: "System";
    thinking: "Thinking";
    toolCalls: {
      command: "Command";
      completed: "Completed";
      count_one: "{{count}} call";
      count_other: "{{count}} calls";
      execute: "Run";
      failed: "Failed";
      files: "Files";
      files_one: "{{count}} file";
      files_other: "{{count}} files";
      input: "Input";
      openParentSession: "View parent session";
      openParentSessionNamed: "View {{title}}";
      output: "Output";
      outputLoadError: "Failed to load output: {{message}}";
      outputLoading: "Loading output…";
      pending: "Pending";
      readFile: "Read {{fileName}}{{range}}";
      readFiles: "Read files";
      running: "Running";
      showLess: "Show less";
      showMore: "Show more";
      subagent: "Using subagent";
      subagentCompleted: "Subagent completed";
      subagentEmpty: "No subagent messages yet.";
      subagentFailed: "Subagent failed";
      subagentPrompt: "Prompt";
      subagentReadOnly: "This subagent session is read-only.";
      subagentResponse: "Subagent response";
      subagentSession: "Subagent session";
      title: "Tool calls";
    };
    turnChanges: {
      added: "added";
      conflict: "Undo blocked: a file changed after this turn.";
      deleted: "deleted";
      editedCount_one: "Edited {{count}} file";
      editedCount_other: "Edited {{count}} files";
      fileCountShort_one: "{{count}} file";
      fileCountShort_other: "{{count}} files";
      fileCount_one: "{{count}} file changed";
      fileCount_other: "{{count}} files changed";
      groupTitle: "Changes";
      kind: {
        binary: "binary";
        document: "document";
        image: "image";
        spreadsheet: "spreadsheet";
        text: "text";
      };
      modified: "modified";
      moreFiles: "+{{count}} more";
      moreFiles_one: "+{{count}} more";
      moreFiles_other: "+{{count}} more";
      notRestorable: "too large to restore";
      partial: "Partial coverage";
      renamed: "renamed";
      restored: "Restored files from this turn.";
      review: "Review";
      showFewerFiles: "Show fewer files";
      showMoreFiles_one: "Show {{count}} more file";
      showMoreFiles_other: "Show {{count}} more files";
      undo: "Undo";
      undoFailed: "Undo failed.";
      undoUnavailable: "Undo is unavailable because a file exceeds the checkpoint size or quota.";
      undone: "Undone";
    };
  };
  browser: {
    actions: {
      back: "Back";
      captureScreenshot: "Capture screenshot";
      clearAnnotations: "Clear all annotations";
      enterDesignMode: "Enter Design Mode";
      exitDesignMode: "Exit Design Mode";
      forward: "Forward";
      reload: "Reload";
      removeAnnotation: "Remove annotation";
      stop: "Stop loading";
    };
    annotations: {
      element: "Element";
      region: "Region {{width}}×{{height}}";
      title: "Annotations ({{count}})";
      title_one: "Annotation ({{count}})";
      title_other: "Annotations ({{count}})";
    };
    placeholder: {
      description: "Enter your dev server URL above to preview your app and use Design Mode to annotate UI elements.";
      title: "Browser Preview";
    };
    states: {
      loadError: "Unable to load page";
      loading: "Loading...";
    };
    urlPlaceholder: "Enter dev server URL (e.g. http://localhost:3000)";
  };
  chat: {
    common: {
      back: "Back";
      cancel: "Cancel";
      save: "Save";
    };
    composer: {
      attachImage: "Attach image";
      placeholder: "Ask anything…";
      removeImage: "Remove image";
      send: "Send";
      stop: "Stop";
    };
    detail: {
      empty: {
        description: "Type below. Press Enter to send. Web search and system prompts can be configured per conversation.";
        noProviderTitle: "Add a model provider to start";
        openProviderSettings: "Open provider settings";
        title: "Send a message to start";
      };
      openSystemPrompt: "Edit system prompt";
      welcome: {
        cta: "New chat";
        description: "Start a free-form conversation with any configured provider. No workspace required.";
        noProvider: "Configure a provider first";
        title: "Pure chat";
      };
    };
    list: {
      archive: "Archive";
      delete: "Delete conversation";
      empty: {
        description: "Start a new chat to begin.";
        title: "No conversations yet";
      };
      heading: "Chats";
      "new": "New chat";
      rename: "Rename";
      renameConversation: "Rename conversation {{title}}";
    };
    message: {
      cancelEdit: "Cancel edit";
      copy: "Copy";
      edit: "Edit";
      error: "Request failed";
      imageAlt: "Attached image";
      regenerate: "Regenerate";
      retry: "Retry";
      submitEdit: "Submit edit";
    };
    modelPicker: {
      noModels: "No provider models configured";
      placeholder: "Select model";
    };
    presets: {
      assistant: {
        label: "General assistant";
      };
      coder: {
        label: "Coding assistant";
      };
      custom: "Custom";
      researcher: {
        label: "Research assistant";
      };
      translator: {
        label: "Translator";
      };
    };
    sidebar: {
      title: "Chat";
    };
    sources: {
      heading: "Sources";
      heading_one: "Sources";
      heading_other: "Sources";
    };
    systemPrompt: {
      description: "Pick a built-in role or write a custom system prompt. Applies to all future turns in this conversation.";
      placeholder: "Optional system prompt…";
      title: "System prompt";
    };
    webSearch: {
      label: "Web search";
      tooltip: "Toggle web search for this conversation";
      unsupported: "Web search is not available for this provider";
    };
  };
  common: {
    actions: {
      attach: "Attach";
      attachFile: "Attach file";
      back: "Back";
      close: "Close";
      closeFile: "Close file";
      closeSearch: "Close search";
      copyCode: "Copy code";
      decrease: "Decrease";
      increase: "Increase";
      send: "Send";
      stop: "Stop";
    };
    agentDescriptions: {
      claudeCli: "Uses the Claude Agent installed and signed in on this computer";
      claudeCode: "Only uses Anthropic Messages models from cocurdex Providers";
      codex: "Fast code generation";
      grokBuild: "Grok's agent runtime over ACP";
      opencode: "Open-source alternative";
      pi: "Built-in agent";
    };
    agents: {
      claudeCli: "Claude Agent";
      codex: "Codex";
      grokBuild: "Grok Build";
      opencode: "OpenCode";
      pi: "Pi";
    };
    jumpToLatest: "Jump to latest";
    jumpToTop: "Jump to top";
    message: {
      showLess: "Show less";
      showMore: "Show more";
    };
    permissions: {
      allowed: "";
      denied: "";
      pending: "";
    };
    relativeTime: {
      lastActiveDays_one: "Last active {{count}} day ago";
      lastActiveDays_other: "Last active {{count}} days ago";
      lastActiveHours_one: "Last active {{count}} hour ago";
      lastActiveHours_other: "Last active {{count}} hours ago";
      lastActiveMinutes_one: "Last active {{count}} minute ago";
      lastActiveMinutes_other: "Last active {{count}} minutes ago";
      lastActiveMonths_one: "Last active {{count}} month ago";
      lastActiveMonths_other: "Last active {{count}} months ago";
      lastActiveNow: "Just now";
      lastActiveYears_one: "Last active {{count}} year ago";
      lastActiveYears_other: "Last active {{count}} years ago";
    };
    states: {
      gitEmptyBranchDescription: "";
      gitEmptyBranchTitle: "";
      gitEmptyCommitDescription: "";
      gitEmptyCommitTitle: "";
      gitEmptyDescription: "";
      gitEmptyStagedDescription: "";
      gitEmptyStagedTitle: "";
      gitEmptyTitle: "";
      gitEmptyUnstagedDescription: "";
      gitEmptyUnstagedTitle: "";
      gitErrorDescription: "";
      gitErrorTitle: "";
      gitFilterEmptyDescription: "";
      gitFilterEmptyTitle: "";
      gitNotRepoDescription: "";
      gitNotRepoTitle: "";
    };
  };
  editor: {
    actions: {
      addToChat: "Add to Chat";
      chatDockTitle: "Chat";
      chatFabHint: "Open chat. Drag to move. Hover and click the close icon to hide this button ({{shortcut}} to show again).";
      closeChat: "Close chat";
      closeChatSessions: "Close session list";
      closeFile: "Close file {{fileName}}";
      edit: "Edit";
      enterEditorFullscreen: "Enter full screen";
      exitEditorFullscreen: "Exit full screen";
      explorer: "Explorer";
      goBack: "Go back";
      goForward: "Go forward";
      hideChatFab: "Hide chat button";
      hideChatFabHint: "Hide this button. {{shortcut}} to show it again.";
      openChat: "Open chat";
      pinChatDock: "Pin chat to the side";
      preview: "Preview";
      resizeChat: "Resize chat";
      resizeExplorer: "Resize explorer panel";
      resizeSessionList: "Resize session list";
      showBrowser: "Browser";
      showEditor: "Files";
      showGitChanges: "Git";
      showIssues: "Issues";
      showNotes: "Notes";
      showPdf: "PDF";
      showTerminal: "Terminal";
      toggleChat: "Toggle chat";
      toggleChatSessions: "Toggle session list";
      toggleEditorPanel: "Toggle editor panel";
      toggleSidebar: "Toggle sidebar";
      unpinChatDock: "Unpin chat";
    };
    breadcrumb: {
      navLabel: "Breadcrumb";
    };
    contextMenu: {
      addToChatReadFailed: "Unable to read this file, so it was not added to chat.";
      addToChatTooLarge: "File is too large to add to chat. Attach a selection instead.";
      copyPath: "Copy Path";
      copyRelativePath: "Copy Relative Path";
      revealInFinder: "Reveal in Finder";
    };
    fileTree: {
      collapseTree: "Collapse workspace tree";
      expandTree: "Expand workspace tree";
      search: "Search files";
      searchPlaceholder: "Search files…";
    };
    git: {
      binaryFile: "Binary file not shown";
      branchLabel: "Branch";
      cancel: "Cancel";
      changeType: {
        added: "Added";
        all: "All changes";
        deleted: "Deleted";
        modified: "Modified";
      };
      changeTypeFilter: "Filter by change type";
      collapseAll: "Collapse all files";
      commit: "Commit";
      commitAndPush: "Commit and push";
      commitAndPushSuccess: "Committed and pushed";
      commitFailed: "Commit failed";
      commitMessage: "Commit message";
      commitMessagePlaceholder: "Commit message (or generate with the button)…";
      commitOrPush: "Commit or push";
      commitSuccess: "Committed";
      copyBranch: "Copy branch name";
      copyPath: "Copy path";
      diffUnavailable: "Diff could not be rendered";
      discard: "Discard";
      discardAll: "Discard all";
      discardAllConfirm_one: "Discard changes in {{count}} visible file? This cannot be undone.";
      discardAllConfirm_other: "Discard changes in {{count}} visible files? This cannot be undone.";
      discardChanges: "Discard changes";
      discardConfirm: "Discard all changes to {{file}}? This cannot be undone.";
      expandAll: "Expand all files";
      fileCount_one: "{{count}} file";
      fileCount_other: "{{count}} files";
      fileTooLarge: "File too large to diff";
      generateCommitMessage: "Generate commit message";
      generateCommitMessageFailed: "Failed to generate commit message";
      generatingCommitMessage: "Generating commit message…";
      includeUnstaged: "Include unstaged changes";
      listView: "List view";
      loadingCommits: "Loading commits…";
      noBranch: "No branch";
      noCommits: "No commits yet";
      noMatchingBranches: "No matching branches";
      push: "Push";
      pushFailed: "Push failed";
      pushSuccess: "Pushed";
      refresh: "Refresh changes";
      scope: {
        branch: "Branch";
        commit: "Commit";
        staged: "Staged";
        unstaged: "Unstaged";
        working: "Working tree";
      };
      scopeMenu: "Diff source";
      searchBranches: "Search branches";
      selectSource: "Source branch";
      selectTarget: "Target branch";
      splitView: "Split view";
      stageAll: "Stage all";
      stageFile: "Stage file";
      toggleFullFile: "Show full file";
      toggleWrap: "Toggle line wrap";
      treeNoSelectionDescription: "Select a file in the tree to view its changes.";
      treeNoSelectionTitle: "No file selected";
      treeSearch: "Filter changed files";
      treeSearchPlaceholder: "Filter files…";
      treeView: "Tree view";
      unifiedView: "Unified view";
      unstageAll: "Unstage all";
      unstageFile: "Unstage file";
    };
    pdf: {
      addPageBookmark: "Bookmark";
      addToNote: "Add to Note";
      addToNoteFailed: "Could not add the selection to the note.";
      addToNoteNoActiveNote: "Notes storage is not ready. Open Notes once, then try again.";
      addedToNewNote: "Created a note and added the selection";
      addedToNote: "Added to note";
      bookmarkPageLabel: "Page {{page}}";
      bookmarks: "Bookmarks";
      closeMarks: "Close bookmarks and highlights";
      closeOutline: "Close outline";
      closeThumbnails: "Close page thumbnails";
      collapseAll: "Collapse all";
      editorHintDescription: "This is a PDF. Open it in the PDF reader tab to view it.";
      editorHintTitle: "PDF files don't open in the code editor";
      expandAll: "Expand all";
      fitPage: "Fit page";
      fitWidth: "Fit width";
      goToPage: "Go to page";
      highlight: "Highlight";
      highlightColor: {
        blue: "Blue";
        green: "Green";
        pink: "Pink";
        yellow: "Yellow";
      };
      highlightColorGroup: "Highlight color";
      highlightWithColor: "Highlight {{color}}";
      highlights: "Highlights";
      loadErrorDescription: "This PDF could not be opened in the reader.";
      loadErrorTitle: "Unable to open PDF";
      markPageBadge: "p.{{page}}";
      marksEmptyDescription: "Bookmark the current page, or select text and highlight it.";
      marksEmptyTitle: "No bookmarks or highlights yet";
      noPdfDescription: "Open a PDF from the file tree to read it here.";
      noPdfTitle: "No PDF open";
      openInReaderAction: "Open in PDF reader";
      outline: "Table of contents";
      pageIndicator: "{{current}} / {{total}}";
      removeBookmark: "Remove bookmark";
      removeHighlight: "Remove highlight";
      removePageBookmark: "Unbookmark";
      resetZoom: "Actual size";
      resizeSidePanel: "Resize PDF side panel";
      search: "Search document";
      searchClose: "Close search";
      searchMatches: "{{current}} / {{total}}";
      searchNext: "Next match";
      searchNoResults: "No results";
      searchPrevious: "Previous match";
      thumbnailError: "—";
      thumbnailLoading: "…";
      thumbnailPage: "Go to page {{page}}";
      thumbnails: "Page thumbnails";
      toggleMarks: "Marks";
      toggleOutline: "Outline";
      toggleSearch: "Search";
      toggleThumbnails: "Thumbnails";
      zoomIn: "Zoom in";
      zoomOut: "Zoom out";
    };
    states: {
      fileReadError: "Unable to read this file in the editor preview.";
      filesLoadError: "Failed to load workspace files.";
      gitEmptyBranchDescription: "The selected branches have no differing files, or one of the refs could not be resolved.";
      gitEmptyBranchTitle: "No branch differences";
      gitEmptyCommitDescription: "This commit did not change any files.";
      gitEmptyCommitTitle: "No changes in commit";
      gitEmptyDescription: "The current workspace has no tracked file changes.";
      gitEmptyStagedDescription: "Nothing is staged yet. Stage files from the working tree to review them here.";
      gitEmptyStagedTitle: "No staged changes";
      gitEmptyTitle: "No git changes";
      gitEmptyUnstagedDescription: "All tracked changes are staged, and there are no untracked files.";
      gitEmptyUnstagedTitle: "No unstaged changes";
      gitErrorDescription: "Git could not read this workspace. Check that git is installed and the repository is intact, then refresh.";
      gitErrorTitle: "Unable to load git changes";
      gitFilterEmptyDescription: "No files match the selected change type.";
      gitFilterEmptyTitle: "No matching changes";
      gitNotRepoDescription: "The current workspace folder is not inside a git repository.";
      gitNotRepoTitle: "Not a git repository";
      loadingFile: "Loading file...";
      loadingGitChanges: "Loading git changes...";
      noFileDescription: "Select a file from the explorer to preview it in the editor area.";
      noFileSelected: "No file selected";
      noWorkspace: "No workspace";
      noWorkspaceDescription: "Select a workspace to inspect git changes.";
      noWorkspaceEditorDescription: "Open a project folder to browse and edit files.";
      noWorkspaceFilesDescription: "Select a workspace to browse files.";
      noWorkspaceTitle: "No workspace selected";
    };
    terminal: {
      closeTab: "Close terminal {{index}}";
      failedToStart: "Failed to start terminal";
      newTab: "New terminal";
      restart: "Restart";
      searchClose: "Close search";
      searchNext: "Next match";
      searchPlaceholder: "Find in terminal";
      searchPrevious: "Previous match";
      selectTab: "Show terminal {{index}}";
      starting: "Starting terminal…";
      tabLabel: "Terminal {{index}}";
    };
  };
  issues: {
    board: {
      addCard: "Add card";
      addColumn: "Add column";
      columnMenu: "Column menu";
      columnsField: "Columns";
      columnsFieldHint: "Columns follow this issue field. Drag a card to update the field.";
      deleteCard: "Delete card";
      deleteColumn: "Delete column";
      deleteColumnConfirm: {
        cancel: "Cancel";
        confirm: "Delete";
        description: '"{{title}}" will be removed from this view. Issues keep their field values.';
        title: "Delete column?";
      };
      displayOptions: "View display";
      displayOptionsHint: "Layout and grouping apply only to this view.";
      dragCard: "Drag card";
      dragColumn: "Drag column";
      groupBy: "Grouping";
      groupByHint: "Rows are grouped by this issue field.";
      groupByPriority: "Priority";
      groupByStatus: "Status";
      layout: "Layout";
      layoutBoard: "Board";
      layoutList: "List";
      renameColumnPrompt: "Column name";
      untitledBoard: "Untitled view";
      untitledCard: "Untitled card";
      untitledColumn: "Untitled column";
    };
    cardMenu: {
      delete: "Delete";
      open: "Open";
      priority: "Priority";
      status: "Status";
    };
    dialog: {
      cancel: "Cancel";
      createIssue: "Create issue";
      descriptionPlaceholder: "Add description…";
      editCard: "Edit issue";
      newIssue: "New issue";
      noProject: "No project";
      priority: "Priority";
      project: "Project";
      save: "Save";
      status: "Status";
      titlePlaceholder: "Issue title";
      unknownProject: "Unknown project";
    };
    empty: {
      description: "Create a card or column to start organizing work.";
      title: "No view yet";
    };
    filter: {
      allProjects: "All projects";
      ariaLabel: "Filter view";
      noProject: "No project";
      project: "Project";
    };
    list: {
      collapseGroup: "Collapse {{title}}";
      createdOn: "Created on {{date}}";
      expandGroup: "Expand {{title}}";
      updatedOn: "Updated on {{date}}";
    };
    scope: {
      private: "Private";
      workspace: "{{name}}";
      workspaceFallback: "Project";
    };
    sidebar: {
      addBoard: "Add view";
      collapse: "Collapse sidebar";
      deleteView: "Delete view";
      deleteViewConfirm: {
        cancel: "Cancel";
        confirm: "Delete";
        description: 'Delete view "{{title}}"? Issues are shared and will not be deleted.';
        title: "Delete view?";
      };
      expand: "Expand sidebar";
      hint: "Issues and views are stored privately by cocurdex.";
      newBoardTitle: "New view";
      renameBoard: "Rename view";
      resize: "Resize sidebar";
      title: "View";
      untitledBoard: "Untitled view";
      views: "Views";
    };
  };
  notes: {
    editor: {
      empty: {
        description: "Select a note from the sidebar or create a new one.";
        title: "No note selected";
      };
      folder: {
        description: "Create a note inside from the sidebar, or rename this folder with the title above.";
        emptyTitle: "Folder";
        renameLabel: "Folder name";
      };
      placeholder: 'Start writing, or press "/" for commands…';
      save: {
        error: "Save failed";
        saved: "Saved";
        saving: "Saving…";
      };
      untitledPlaceholder: "Untitled";
    };
    scope: {
      private: "Private";
      workspace: "{{name}}";
      workspaceFallback: "Project";
    };
    sidebar: {
      collapse: "Collapse sidebar";
      collapseFolder: "Collapse folder";
      delete: "Delete";
      deleteConfirm: {
        cancel: "Cancel";
        confirm: "Delete";
        descriptionFolder: "This folder and everything inside it will be permanently deleted.";
        descriptionNote: "This note will be permanently deleted.";
        title: 'Delete "{{title}}"?';
      };
      dropToRoot: "Drop here for top level";
      empty: {
        description: "Create your first note to start writing.";
        title: "No notes yet";
      };
      expand: "Expand sidebar";
      expandFolder: "Expand folder";
      moveTo: "Move to";
      moveToRoot: "Top level";
      newFolder: "New folder";
      newFolderDefaultTitle: "New folder";
      newFolderInside: "New folder inside";
      newNote: "New note";
      newNoteInside: "New note inside";
      rename: "Rename";
      resize: "Resize sidebar";
      title: "Notes";
      untitled: "Untitled";
    };
    slash: {
      empty: "No matching blocks";
      items: {
        blockquote: "Quote";
        bulletList: "Bulleted list";
        codeBlock: "Code block";
        divider: "Divider";
        heading1: "Heading 1";
        heading2: "Heading 2";
        heading3: "Heading 3";
        orderedList: "Numbered list";
        paragraph: "Text";
        taskList: "To-do list";
      };
    };
  };
  onboarding: {
    action: {
      configureProviders: "Configure providers";
      dontShowAgain: "Don't show this again";
      enterApp: "Go to cocurdex";
      openProject: "Open a project folder";
      openProjectHint: "Agents run inside the folder you pick. This is the main way to use cocurdex.";
      skip: "Skip";
      startChat: "Go to chat";
    };
    description: "cocurdex runs coding agents against a local folder. Here is what is available on this machine.";
    providers: {
      description: "Add a provider and enable the models you want. The built-in pi agent needs one; the other adapters bring their own.";
      title: "Configure a model provider";
    };
    title: "Welcome to cocurdex";
  };
  search: {
    empty: {
      error: {
        description: "ripgrep could not list files for this workspace.";
        title: "Unable to index files";
      };
      loading: {
        description: "Indexing the workspace with ripgrep.";
        title: "Loading files...";
      };
      noFiles: {
        description: "The workspace did not return any searchable files.";
        title: "No files found";
      };
      noMatches: {
        description: "Try a different filename or path.";
        title: "No matching files";
      };
      noWorkspace: {
        description: "Open a workspace before searching files.";
        title: "No workspace selected";
      };
      typeToSearch: {
        description: "";
        title: "Type to search for files";
      };
    };
    files: "Files";
    fullText: {
      caseSensitive: "Match case";
      clearResults: "Clear search results";
      collapseAll: "Collapse all";
      emptyQueryDescription: "Search across the current workspace by file contents.";
      emptyQueryTitle: "Search file contents";
      error: "Error";
      errorDescription: "ripgrep could not complete this search.";
      errorTitle: "Search failed";
      expandAll: "Expand all";
      fileMatchCount_one: "{{count}} match";
      fileMatchCount_other: "{{count}} matches";
      filesToExclude: "files to exclude";
      filesToInclude: "files to include";
      globPlaceholder: "e.g. *.ts, src/**, .claude";
      inputLabel: "Search file contents";
      matchCount_one: "{{count}} match";
      matchCount_other: "{{count}} matches";
      noMatchesDescription: "Try a different term or change the search options.";
      noMatchesTitle: "No text matches";
      placeholder: "Search file contents...";
      resultsInFiles_one: "{{count}} result in {{fileCount}} files";
      resultsInFiles_other: "{{count}} results in {{fileCount}} files";
      searching: "Searching...";
      toggleFilters: "Toggle search details";
      useRegex: "Use regular expression";
      wholeWord: "Match whole word";
    };
    headings: {
      all: "All files";
      recent: "Recently opened";
      results: "Results";
    };
    more: "More";
    openSearch: "Open search";
    placeholder: "Search files by name or path...";
    searchFiles: "Search files";
  };
  sessions: {
    branch: {
      branches: "Branches";
      empty: "No matching branches.";
      noBranch: "No branch";
      searchPlaceholder: "Search branches";
      switchFailed: "Could not switch to {{branch}}. Check the working tree and try again.";
    };
    collaborationMode: {
      default: "Default";
      label: "Collaboration mode";
      plan: "Plan";
      planMode: "Plan mode";
    };
    composer: {
      agentStatus: {
        detecting: "Checking…";
        error: "Unavailable";
        notInstalled: "Not installed";
        updateRequired: "Update required";
      };
      contextFileTooLarge: "File is too large. Select a smaller file or attach a selection.";
      noInstalledAgent: "No agent installed";
      placeholder: "Plan, Build, / for skills, @ for context";
      removeAttachment: "Remove attachment";
      selectAgent: "Select agent";
      sendFollowUp: "Send follow-up...";
      sendFollowUpCompact: "Send follow-up";
      thinkingLevel: "Reasoning effort";
      thinkingLevelWithValue: "Reasoning {{level}}";
      thinkingLevels: {
        default: "Default";
        high: "High";
        low: "Low";
        max: "Max";
        medium: "Medium";
        minimal: "Minimal";
        off: "Off";
        ultra: "Ultra";
        xhigh: "XHigh";
      };
      treeOutline: "Tree outline";
    };
    defaultTitle: "New {{agentLabel}} session";
    modelMenu: {
      defaultTag: "Default";
      empty: "No matching models.";
      emptyUnconfigured: "No providers configured yet.";
      fastMode: "Fast Mode";
      fastModeOff: "Off";
      fastModeOn: "On";
      mcp: "MCP";
      mcpNone: "None";
      mcpNoneConfigured: "No MCP servers reported";
      mcpServers: "MCP servers";
      mcpStatuses: {
        connected: "Connected";
        connecting: "Connecting";
        disabled: "Disabled";
        failed: "Failed";
        unknown: "Unknown";
      };
      mcpSummary: "{{connected}}/{{total}} connected";
      openCodeAgent: "Collaboration mode";
      openCodeAgentDefault: "Default";
      openCodeVariant: "Reasoning effort";
      openCodeVariantDefault: "Default";
      openProviderSettings: "Configure providers";
      reasoningEffort: "Reasoning effort";
      reset: "Reset to default";
      searchPlaceholder: "Search models...";
      selectModel: "Select model";
      serviceTierStandard: "Standard";
      speed: "Speed";
      triggerLabel: "Model";
    };
    permissionMode: {
      changedForModel: "{{model}} does not support Auto mode. Switched to Default permissions.";
      "claude-accept-edits": "Accept edits";
      "claude-auto": "Auto mode";
      "claude-bypass-permissions": "Bypass permissions";
      "claude-default": "Default permissions";
      "claude-plan": "Plan";
      "codex-auto": "Auto";
      "codex-full-access": "Full Access";
      "codex-read-only": "Read Only";
      descriptions: {
        "claude-accept-edits": "Applies file edits automatically; still asks for commands";
        "claude-auto": "Claude decides when to ask";
        "claude-bypass-permissions": "Skips every permission prompt";
        "claude-default": "Asks before edits and commands";
        "claude-plan": "Plans only; no edits or commands";
        "codex-auto": "Edits workspace files and runs commands; asks before network or outside edits";
        "codex-full-access": "Never asks; can edit files outside the workspace and reach the network";
        "codex-read-only": "Reads workspace files; asks before edits or network access";
        "grok-always-approve": "Approves every tool call automatically";
        "grok-ask": "Asks before every tool call";
        "grok-auto": "Grok decides when to ask";
        "opencode-allow": "Approves every tool call automatically";
        "opencode-ask": "Asks before every tool call";
        "opencode-deny": "Rejects every tool call that needs permission";
      };
      "grok-always-approve": "Approve all";
      "grok-ask": "Ask each time";
      "grok-auto": "Auto decide";
      label: "Permission mode";
      "opencode-allow": "Allow";
      "opencode-ask": "Ask";
      "opencode-deny": "Deny";
      unavailableForModel: "{{model}} does not support this mode.";
    };
    sidebar: {
      addProject: "Add project";
      archive: "Archive";
      collapseChildren: "Collapse subagent sessions";
      delete: "Delete";
      expandChildren: "Expand subagent sessions";
      marketplace: "Marketplace";
      newSession: "New session";
      newSessionInWorkspace: "New session in {{workspaceName}}";
      noAgentsYet: "No sessions yet";
      pendingAttention: "Needs attention";
      projectsGroup: "Work";
      removeProject: "Remove";
      rename: "Rename";
      renameSession: "Rename {{title}}";
      revealInFileManager: "Reveal in file manager";
      running: "Running";
      settings: "Settings";
    };
    workspace: {
      dropFolderDescription: "Release to open it as a project.";
      dropFolderTitle: "Drop folder to open";
      empty: "No matching workspaces.";
      emptyTitle: "Open a project to start";
      emptyUnconfigured: "No workspaces yet.";
      enterProject: "Enter project";
      home: "Home";
      openFolder: "Open Folder";
      recents: "Recents";
      removeFailed: "Could not remove this workspace. Try again.";
      startDescription: "Pick a model, describe the task, and keep the first prompt scoped.";
      startTitle: "What should we do in {{workspaceName}}?";
      startTitleAfter: "?";
      startTitleBefore: "What should we do in";
      workspace: "Workspace";
    };
  };
  settings: {
    adapters: {
      action: {
        copyCommand: "Copy command";
        copyPath: "Copy path";
        docs: "Docs";
        refresh: "Refresh";
      };
      badge: {
        builtin: "Built in";
        updateRequired: "Update required";
      };
      description: "cocurdex runs these agent CLIs on this machine. Install or update the ones you want to pick for new sessions.";
      kind: {
        builtin: "Built-in";
        detecting: "Checking…";
        error: "Failed";
        missing: "Not installed";
        outdated: "Update required";
        ready: "Ready";
      };
      rateLimits: {
        authenticationRequired: "No usage found. Not signed in. Run claude auth login, then refresh.";
        failed: "Could not read usage: {{message}}";
        loading: "Loading usage…";
        timedOut: "Usage check timed out. Try refreshing.";
        unknownError: "Unknown error";
      };
      status: {
        builtin: "Built in — ships with cocurdex, nothing to install.";
        detecting: "Checking installation…";
        error: "Detection failed.";
        missing: "Not installed — `{{executable}}` was not found on PATH.";
        outdated: "Installed {{installed}} is below the required {{minimum}}.";
        outdatedHint: "Still usable. Some capabilities may not work until you update.";
        ready: "Installed and ready.";
      };
      toast: {
        commandCopied: "Install command copied";
        pathCopied: "Path copied";
        refreshFailed: "Could not refresh adapters";
      };
    };
    appearance: {
      groupTitle: "Appearance";
      modes: {
        dark: "Dark";
        light: "Light";
        system: "System";
      };
      preset: {
        description: "Color palette applied to both light and dark modes. cocurdex is the default product look.";
        empty: "No themes found";
        searchPlaceholder: "Search themes...";
        title: "Color theme";
      };
      theme: {
        description: "Choose between light, dark, or system themes.";
        title: "Theme";
      };
      typography: {
        codeFontFamily: {
          description: "Font used in code editors and diffs.";
          system: "System monospace";
          title: "Code font family";
        };
        codeFontSize: {
          description: "Font size for code editors and diffs.";
          title: "Code font size";
        };
        fontEmpty: "No fonts found";
        fontSearchPlaceholder: "Search fonts...";
        groupTitle: "Typography";
        uiFontFamily: {
          description: "Font used across the application interface.";
          system: "System font";
          title: "UI font family";
        };
        uiFontSize: {
          description: "Base font size for the application interface.";
          title: "UI font size";
        };
      };
    };
    chatDisplay: {
      activity: {
        description: "How reasoning and tool calls show up before each answer. Collapsed per turn by default; expand for details.";
        options: {
          condensed: "Collapse by turn";
          expanded: "Expand everything";
          hidden: "Hide completely";
        };
        title: "Process display";
      };
      groupTitle: "Conversation display";
      hideFab: {
        description: "When chat is closed in floating or pinned layout, hide the bottom-right button. Open chat again with {{shortcut}}.";
        title: "Hide chat button when closed";
      };
      layout: {
        description: "How chat sits relative to the editor. Restored on next launch.";
        options: {
          center: "Center column";
          float: "Floating dock";
          pinned: "Pinned right rail";
        };
        title: "Chat layout";
      };
    };
    cli: {
      actions: {
        install: "Install";
        refresh: "Refresh";
        reinstall: "Repair";
        uninstall: "Uninstall";
      };
      description: "Install the cocurdex command so terminals and agents can call the CLI.";
      groupTitle: "Command line";
      loading: "Checking CLI install…";
      status: {
        foreignInstall: "Another cocurdex command exists at {{path}}. Repair to point it at this app.";
        installedNotOnPath: "Installed at {{path}}, but that folder is not on PATH. Open a new terminal or add it to PATH.";
        notInstalled: "The cocurdex command is not installed for this user.";
        ready: "Ready. Terminals can run cocurdex ({{path}}).";
      };
      title: "Shell command";
      toast: {
        installFailed: "Could not install the cocurdex command";
        installed: "cocurdex command installed";
        uninstallFailed: "Could not uninstall the cocurdex command";
        uninstalled: "cocurdex command removed";
      };
    };
    daemon: {
      actions: {
        refresh: "Check status";
        restart: "Restart";
        start: "Start";
      };
      description: "The local cocurdex daemon holds the app database and agent sessions. Restart it if notes, issues, or agents stop responding.";
      details: {
        protocol: "Protocol version {{version}}";
        runtime: "Runtime {{fingerprint}}";
        socket: "Socket {{path}}";
        startedAt: "Started {{value}}";
      };
      groupTitle: "Daemon";
      loading: "Checking daemon status…";
      status: {
        outdated: "Running (pid {{pid}}), but the runtime does not match this app. Restart to replace it.";
        running: "Running (pid {{pid}}).";
        runningOwned: "Running (pid {{pid}}), managed by this app.";
        stopped: "Not running. Start or restart to bring it back.";
      };
      title: "Local daemon";
      toast: {
        restartFailed: "Could not restart the daemon";
        restarted: "Daemon restarted";
      };
    };
    followUp: {
      description: "Queue follow-ups until the current run finishes, or steer an active run when supported. Press {{shortcut}} to use the opposite behavior for one message.";
      groupTitle: "Agent behavior";
      options: {
        queue: "Queue";
        steer: "Steer";
      };
      title: "Follow-up behavior";
    };
    git: {
      commitMessageModel: {
        agentDescription: "Agent used to generate Git commit messages.";
        agentLabel: "Agent";
        footnote: "When the commit message is left blank, the selected model generates a Conventional Commits subject from the staged changes. If no model is set, you must type a message yourself.";
        group: "Commit messages";
        modelDescription: "Model used to generate Git commit messages.";
        modelLabel: "Model";
        noModels: "No compatible models";
        none: "None (type message manually)";
        saveFailed: "Failed to update commit message model";
      };
    };
    groups: {
      advanced: "Other";
      core: "Basic";
      workspace: "Workflow";
    };
    language: {
      description: "Choose the interface language used by product UI.";
      empty: "No languages found";
      groupTitle: "Language";
      modes: {
        system: "System";
      };
      searchPlaceholder: "Search languages...";
      title: "Interface language";
    };
    licenses: {
      chromiumDescription: "Chromium and Electron third-party notices are kept in a separate credits file shipped with the app.";
      chromiumOpen: "Open Chromium licenses";
      chromiumTitle: "Chromium / Electron";
      chromiumUnavailable: "Chromium license file is not available in this build.";
      description: "Third-party notices for bundled dependencies";
      dialogDescription: "License texts for software bundled with Cocurdex.";
      dialogTitle: "Open source licenses";
      empty: "Try a different name, license, or version.";
      emptyTitle: "No matching packages";
      loadError: "The bundled license catalog could not be read.";
      loadErrorTitle: "Could not load licenses";
      loading: "Loading licenses…";
      noLicenseText: "No license text was bundled for this package.";
      packageCount: "{{total}} packages";
      packageCountFiltered: "{{visible}} of {{total}}";
      retry: "Retry";
      searchPlaceholder: "Search packages";
      title: "Open source licenses";
      view: "View";
    };
    mcp: {
      description: "Configure the MCP servers available to the built-in Pi agent. Servers connect only when Pi uses one of their tools.";
      editorLabel: "MCP server configuration";
      form: {
        add: "Add server";
        arguments: "Arguments";
        argumentsDescription: "Enter one argument per line.";
        argumentsPlaceholder: "-y\npackage-name";
        command: "Command";
        commandPlaceholder: "npx";
        emptyDescription: "Add a local command or remote endpoint to make its tools available to Pi.";
        emptyTitle: "No MCP servers configured";
        environment: "Environment variables";
        environmentDescription: "Enter one KEY=value pair per line.";
        environmentPlaceholder: "API_KEY=${API_KEY}";
        local: "Local";
        name: "Server name";
        namePlaceholder: "github";
        remote: "Remote";
        remove: "Remove server";
        servers: "Servers";
        transport: "Connection";
        url: "Server URL";
        urlPlaceholder: "https://example.com/mcp";
      };
      mode: {
        form: "Form";
        json: "JSON";
        label: "Configuration mode";
      };
      restartHint: "Changes apply when a Pi session starts. Existing running sessions keep their current tools.";
      save: "Save";
      saved: "MCP configuration saved";
      saving: "Saving";
      title: "MCP";
    };
    network: {
      proxy: {
        allProxy: {
          description: "Optional catch-all proxy (ALL_PROXY), for example socks5://127.0.0.1:1080. Agent CLIs may use this when HTTP/HTTPS proxies are unset.";
          placeholder: "socks5://127.0.0.1:1080";
          title: "All / SOCKS proxy";
        };
        credentialsNote: "Proxy URLs are stored as plain text in app settings and are passed to Agent subprocesses. Avoid embedding credentials you would not want a spawned CLI to read.";
        groupTitle: "Network proxy";
        httpProxy: {
          description: "HTTP proxy URL. Example: http://127.0.0.1:7890 or http://user:pass@host:port.";
          placeholder: "http://127.0.0.1:7890";
          title: "HTTP proxy";
        };
        httpsProxy: {
          description: "HTTPS proxy URL. Leave empty to reuse the HTTP proxy.";
          placeholder: "Same as HTTP proxy";
          title: "HTTPS proxy";
        };
        invalidUrl: "{{field}} must be a full URL with a scheme, e.g. http://127.0.0.1:7890";
        loading: "Loading proxy settings…";
        manualGroupTitle: "Manual proxy";
        manualIncomplete: "Manual mode is selected but no proxy address is set, so traffic still goes direct.";
        modeTitle: "Proxy mode";
        modes: {
          manual: "Manual";
          off: "Off";
          system: "System / environment";
        };
        noProxy: {
          description: "Comma-separated hosts that bypass the proxy. Localhost is recommended so app IPC stays direct.";
          placeholder: "localhost,127.0.0.1,::1,.local";
          title: "Bypass list (NO_PROXY)";
        };
        notesBody: "Applies to Agent subprocesses (including ACP), app and daemon model/API requests, and Chromium network traffic. Does not change your system proxy or force the integrated terminal to use these settings. Restart an active agent session after changing proxy settings so the new environment is picked up.";
        notesGroupTitle: "Scope";
        saveFailed: "Failed to save proxy settings";
        scopeDescription: "Used for Agents and app outbound network requests. Does not hijack the system proxy or the integrated terminal by default.";
        status: {
          checking: "Checking connectivity…";
          idle: "Hover to check connectivity";
          label: "Proxy status";
          offDetail: "Outbound traffic is direct; no app proxy is applied.";
          openSettings: "Open network settings";
        };
        test: {
          action: "Test";
          description: "Sends one request to ipinfo.io through the app's outbound path and reports the egress address, so you can tell whether the proxy is really in use.";
          failure: "Failed: {{error}}";
          success: "Reachable in {{durationMs}} ms — egress IP {{ip}}";
          title: "Test connectivity";
          unknownIp: "unknown";
        };
      };
    };
    notifications: {
      completed: {
        body: "An agent run has completed.";
        title: "Agent finished";
      };
      completionSound: {
        description: "Play a sound when an agent finishes responding.";
        title: "Completion sound";
      };
      groupTitle: "Notifications";
      permission: {
        body: "An agent is waiting for permission approval.";
        title: "Approval needed";
      };
      question: {
        body: "An agent is waiting for your answer.";
        title: "Agent needs input";
      };
      systemNotifications: {
        description: "Show a system notification when an agent finishes or needs your attention.";
        title: "System notifications";
      };
    };
    placeholder: {
      description: "This group is reserved as a placeholder. Add concrete fields and interactions after the information architecture is settled.";
      title: "{{section}} placeholder";
    };
    providers: {
      actions: {
        add: "Add";
        clearKey: "Clear key";
        delete: "Delete";
        importJson: "Import JSON";
        newProvider: "New provider";
        refresh: "Refresh";
        save: "Save";
      };
      auth: {
        accountDescription: "Use a provider account or subscription through Pi OAuth.";
        apiKeyDescription: "Use an API key managed by Pi.";
        cancel: "Cancel";
        connected: "Connected";
        continue: "Continue";
        deviceCode: "Enter code {{code}} in the browser.";
        loginFailed: "Unable to authenticate with this provider";
        logoutFailed: "Unable to sign out";
        readFailed: "Unable to read provider authentication";
        signOut: "Sign out";
        starting: "Starting authentication…";
        title: "Authentication";
        useMethod: "Use";
        waitingForBrowser: "Waiting for browser…";
      };
      deleteConfirm: {
        cancel: "Cancel";
        confirm: "Delete";
        description: "Delete {{provider}} and all of its models? This cannot be undone.";
        title: "Delete provider";
      };
      details: {
        title: "Provider details";
      };
      empty: {
        noMatches: "No matching providers";
      };
      fields: {
        apiKey: "API key";
        baseUrl: "Base URL";
        capabilities: "Capabilities";
        capability: {
          agent: "Agent";
          chat: "Chat";
          reasoning: "Reasoning";
          vision: "Vision";
        };
        contextLimit: "Context";
        costJson: 'Cost JSON, e.g. {"input":3,"output":15}';
        displayName: "Display name";
        headersJson: 'Custom headers JSON, e.g. {"x-api-version":"1"}';
        modelCompatJson: "Model compatibility JSON";
        modelId: "Model ID";
        modelRuntime: "Model runtime";
        newApiKey: "New API key";
        outputLimit: "Output";
        providerCompatJson: "Provider compatibility JSON";
        providerId: "Provider ID";
        reasoning: "Supports reasoning";
        thinkingLevelMapJson: 'Thinking level map JSON, e.g. {"high":10000}';
      };
      header: {
        description: "Configure service endpoints, models, and agent defaults.";
        title: "Provider management";
      };
      importJson: {
        back: "Back";
        confirm: "Import";
        description: "Paste a pi-style models.json. Each provider is upserted with its models. Literal apiKey values are stored; $ENV and !command keys must be set manually.";
        importing: "Importing…";
        title: "Import JSON";
        warnings: {
          authHeaderNoKey: 'Provider "{{id}}": authHeader is set but no literal apiKey was provided.';
          commandApiKey: 'Provider "{{id}}": shell-command apiKey (!…) is not run on import; set the key manually.';
          envApiKey: 'Provider "{{id}}": environment apiKey ($…) is not expanded on import; set the key manually.';
          oauthIgnored: 'Provider "{{id}}": oauth config is ignored on import.';
        };
      };
      list: {
        configuredCount: "{{count}} configured";
      };
      models: {
        addTitle: "Add model";
        columns: {
          capabilities: "Capabilities";
          compat: "Compat";
          cost: "Cost / 1M";
          defaultModel: "Default";
          input: "Input";
          no: "No";
          reasoning: "Reasoning";
          reasoningEfforts: "Reasoning options";
          serviceTiers: "Service tiers";
          thinking: "Thinking map";
          yes: "Yes";
        };
        empty: "No models configured for {{provider}}.";
        modelCount: "{{count}} models";
        modelCount_one: "{{count}} model";
        modelCount_other: "{{count}} models";
        noMatches: "No matching models";
        parametersFor: "{{model}} parameters";
        parametersTitle: "Model parameters";
        runtimeFor: "{{model}} runtime";
        searchPlaceholder: "Search models...";
        showingCount: "Showing {{visible}} of {{total}} models";
        title: "Models";
        toggleFor: "Toggle {{model}}";
      };
      searchPlaceholder: "Search providers...";
      sections: {
        advanced: "Advanced";
        auth: "Auth";
        provider: "Provider";
      };
      select: "Select";
      state: {
        configured: "Configured";
        disabled: "Disabled";
        enabled: "Enabled";
        keySet: "Key set";
        noKey: "No key";
        notConfigured: "Not configured";
      };
      status: {
        deleteFailed: "Unable to delete provider";
        idExists: "Provider ID {{id}} already exists";
        importFailed: "Unable to import providers";
        importSucceeded: "Imported {{count}} provider(s)";
        importSucceeded_one: "";
        importSucceeded_other: "";
        missingFields: "Required fields are missing";
        modelDisabled: "Model disabled";
        modelEnabled: "Model enabled";
        modelSaved: "Model saved";
        modelsRefreshFailed: "Unable to refresh models";
        modelsRefreshed: "Models refreshed";
        providerDeleted: "Provider deleted";
        providerSaved: "Provider saved";
        refreshingModels: "Refreshing models...";
        saveFailed: "Unable to save provider";
      };
      templates: {
        description: "Pick a preset, save it, then choose an available authentication method.";
        title: "Add a provider";
      };
      titleModel: {
        description: "Generates titles for the built-in Pi agent and chat conversations. Other agents use their own title support.";
        label: "Pi title generation model";
        none: "Use current model";
        probeFailed: "Failed · {{latencyMs}} ms · {{error}}";
        probeOk: "Connected · {{latencyMs}} ms";
        probeOkWithTitle: "Connected · {{latencyMs}} ms · “{{title}}”";
        saveFailed: "Failed to update title model";
        selectModelFirst: "Select a title model first";
        test: "Test";
        testing: "Testing…";
      };
    };
    sections: {
      about: "About";
      adapters: "Adapters";
      appearance: "Appearance";
      archived: "Archived chats";
      computer: "Computer use";
      environment: "Network";
      general: "General";
      git: "Git";
      licenses: "Open source licenses";
      mcp: "MCP";
      personalization: "Personalization";
      providers: "Providers";
      shortcuts: "Shortcuts";
      skills: "Skills";
      usage: "Usage";
      workspace: "Worktrees";
    };
    sendShortcut: {
      description: "Choose when Enter sends a prompt or inserts a new line.";
      options: {
        "command-enter": "{{shortcut}} always";
        "command-enter-multiline": "{{shortcut}} for multiline prompts";
        enter: "Enter";
      };
      title: "Send shortcut";
    };
    shortcuts: {
      actions: {
        fileSearch: {
          description: "Open the workspace file search palette.";
          title: "Search files";
        };
        toggleChatDock: {
          description: "Show or hide the floating/pinned chat dock when the editor is fullscreen.";
          title: "Toggle chat dock";
        };
        toggleDesignMode: {
          description: "Toggle browser design annotation mode.";
          title: "Toggle design mode";
        };
        toggleEditorFullscreen: {
          description: "Expand the editor to fullscreen (floating/pinned chat) or return to the center chat layout.";
          title: "Toggle editor fullscreen";
        };
        toggleLeftSidebar: {
          description: "Show or hide the left sidebar.";
          title: "Toggle left sidebar";
        };
        toggleRightPanel: {
          description: "Show or hide the editor panel.";
          title: "Toggle editor panel";
        };
        toggleWorkspaceSearch: {
          description: "Open workspace search in the editor panel.";
          title: "Search in workspace";
        };
      };
      categories: {
        browser: "Browser";
        chat: "Chat";
        editor: "Editor";
        general: "General";
        layout: "Layout";
      };
      conflict: "Conflicts with {{action}}";
      description: "Click a binding to record a new chord. Escape cancels recording; Backspace clears the binding.";
      editBinding: "Edit shortcut {{binding}}";
      emptyDescription: "Try a different name or category.";
      emptyTitle: "No shortcuts match";
      hint: "Shortcuts pause while a binding is being recorded. Changes are saved automatically.";
      recording: "Press keys…";
      reset: "Reset to default";
      resetAll: "Reset all";
      searchPlaceholder: "Search shortcuts…";
      unbound: "None";
    };
    sidebar: {
      resize: "Resize settings sidebar";
    };
    skills: {
      actions: {
        install: "Install";
        refresh: "Refresh";
        reinstall: "Reinstall";
        remove: "Remove";
        update: "Update";
      };
      cliHint: "CLI: cocurdex skills install --scope project|global  ·  cocurdex skills status --scope project|global";
      groupTitle: "Install location";
      intro: "Install cocurdex product skills so agents (Claude, OpenCode, Pi, and others) can run Notes and Issues workflows. Installation is manual — nothing is written until you install.";
      loading: "Checking skill install…";
      scope: {
        global: {
          description: "Install under ~/.agents/skills and ~/.claude/skills for every project on this machine.";
          title: "Global (all projects)";
        };
        project: {
          description: "Install into the active workspace (.agents/skills and .claude/skills). Good for team repos you commit.";
          title: "This project";
        };
      };
      status: {
        conflict: "Unmanaged cocurdex skill folders already exist ({{skills}}). Remove or rename them under {{path}}, then install again.";
        installed: "Installed v{{version}} at {{path}}";
        noWorkspace: "Select a project workspace first to install project-level skills.";
        notInstalled: "Not installed. Would write to {{path}}";
        updateAvailable: "Installed v{{installed}}; pack v{{latest}} is available at {{path}}";
      };
      toast: {
        alreadyInstalled: "Skills are already up to date";
        conflict: "Could not install: conflict with existing skills ({{skills}})";
        installFailed: "Could not install skills";
        installed: "cocurdex skills installed";
        removeFailed: "Could not remove skills";
        removed: "cocurdex skills removed";
        updated: "cocurdex skills updated";
      };
      workspaceLabel: "Active project: {{name}}";
    };
    updates: {
      actions: {
        check: "Check for updates";
        install: "Update and Restart";
      };
      card: {
        body: "Version {{version}} is ready. It will take effect after restart.";
        changelog: "View release notes";
        install: "Update and Restart";
        later: "Later";
        title: "Update available";
      };
      description: "Installed version {{version}}.";
      groupTitle: "App";
      status: {
        checking: "Checking for updates…";
        downloading: "Downloading version {{version}}…";
        error: "Could not check for updates. {{message}}";
        ready: "Version {{version}} is downloaded and ready to install.";
        unsupported: "Automatic updates are available in the packaged app.";
        upToDate: "You're up to date.";
      };
      title: "Version";
    };
  };
}
