// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  agent: {
    activity: {
      attention: "Attention needed";
      completed: "Completed";
      planning: "Working";
      ready: "Ready";
      reasoningCount_one: "{{count}} reasoning step";
      reasoningCount_other: "{{count}} reasoning steps";
      replyCount_one: "{{count}} interim reply";
      replyCount_other: "{{count}} interim replies";
      responding: "Replying";
      thinking: "Thinking";
      toolCount_one: "{{count}} tool call";
      toolCount_other: "{{count}} tool calls";
      usingTools: "Using tools";
      workedFor: "Worked for {{duration}}";
    };
    assistantMessage: {
      copy: "Copy response";
      copyRichText: "Copy Rich Text";
      turnUsage: {
        ariaLabel: "Token usage this turn";
        cacheHitRate: "Cache hit rate";
        cacheRead: "Cache read";
        cacheWrite: "Cache write";
        input: "Total input";
        newInput: "Uncached input";
        output: "Output";
      };
    };
    contextBreakdown: {
      groups: {
        agents: "Agents";
        deferredTools: "Deferred tools";
        mcpTools: "MCP tools";
        memoryFiles: "Memory files";
        skills: "Skills";
        slashCommands: "Slash commands";
        systemPrompt: "System prompt";
        systemTools: "System tools";
      };
      title: "Context usage";
    };
    contextWindow: {
      cacheReadTokens: "Cache read: {{tokens}}";
      cacheWriteTokens: "Cache write: {{tokens}}";
      currentContext: "Current context";
      inputTokens: "Input: {{tokens}}";
      label: "Context window usage";
      outputTokens: "Output: {{tokens}}";
      reasoningTokens: "Reasoning: {{tokens}}";
      sessionTotals: "Session totals";
      tooltip: "{{percent}}% of context limit";
    };
    imagePreview: {
      closePreview: "Close image preview";
      copied: "Copied";
      copyFailed: "Copy failed";
      copyImage: "Copy image";
      downloadImage: "Download image";
      imagePosition: "{{current}} / {{total}}";
      nextImage: "Next image";
      previousImage: "Previous image";
      resetView: "Reset view";
      resetZoom: "Reset zoom";
      rotate: "Rotate clockwise";
      zoomIn: "Zoom in";
      zoomOut: "Zoom out";
    };
    jumpToLatest: "Jump to latest";
    jumpToTop: "Jump to top";
    navigation: {
      collapse: "Collapse navigation";
      expand: "Expand navigation";
      jumpToPrompt: "Jump to prompt {{index}}";
    };
    openFile: "Open file";
    peerMessage: {
      from: "From session {{title}}";
      fromScriptRun: "From script {{name}}";
    };
    permissions: {
      actions: {
        edit: "edit";
        read: "read";
        use: "use";
        write: "write";
      };
      allow: "Allow";
      allowOnce: "Allow once";
      allowed: "Allowed";
      alwaysAllow: "Always allow";
      claudeAction: "Allow Claude to {{action}} {{target}}?";
      command: "Command";
      denied: "Denied";
      deny: "Deny";
      files: "Files";
      path: "Path";
      pattern: "Pattern";
      pending: "Pending";
      query: "Query";
      rejectAlways: "Reject always";
      resolveFailed: "This request is no longer active.";
      runCommand: "Run this command?";
      showLess: "Show less";
      showMore: "Show full command";
      title: "Permission approval";
      url: "URL";
    };
    plan: {
      collapse: "Collapse tasks";
      dismiss: "Hide tasks";
      expand: "Expand tasks";
      label: "Tasks";
      progress: "{{done}}/{{count}}";
      progress_one: "";
      progress_other: "";
    };
    planApproval: {
      abandon: "Abandon plan";
      approve: "Approve and implement";
      collapse: "Show less";
      copy: "Copy plan";
      emptyHeading: "No plan written yet";
      emptySubtitle: "The agent left plan mode without writing a plan.";
      expand: "Show full plan ({{count}} lines)";
      expandMore: "Show more";
      expand_one: "";
      expand_other: "";
      feedbackDismiss: "Back";
      feedbackLabel: "What should change? Leave empty and the agent will ask.";
      feedbackPlaceholder: "e.g. keep proxy.ts untouched, only edit the README";
      feedbackSend: "Send changes";
      heading: "The agent wrote a plan";
      pending: "Waiting on you";
      requestChanges: "Request changes";
      resolvedAbandoned: "Plan abandoned";
      resolvedApproved: "Plan approved";
      resolvedCancelled: "Changes requested";
      resolvedStale: "Replaced by a newer plan";
      subtitle: "Approve it to start implementing, or send it back for changes.";
      title: "Plan approval";
      waiting: "Waiting on plan approval";
      waitingEmpty: "No plan written — approve or request changes";
    };
    previousMessage: {
      cancel: "Cancel";
      cancelEdit: "Cancel edit";
      copy: "Copy prompt";
      dialogDescription: "Submitting from a previous message will clear the messages after this one. Reverting also restores files to their checkpoint before this message.";
      dialogTitle: "Submit from a previous message?";
      dontAskAgain: "Don't ask again";
      dontRevert: "Don't revert";
      edit: "Edit previous message";
      revert: "Revert";
      revertUnavailable: "File revert is unavailable because this message has no git workspace checkpoint.";
      submitEdit: "Submit edited message";
    };
    questions: {
      answer: "Answer";
      answered: "Answered";
      pending: "Pending";
      placeholder: "Answer the question...";
      title: "Question";
    };
    queue: {
      actionFailed: "Queue action failed";
      cancel: "Cancel";
      delete: "Remove from queue";
      edit: "Edit message";
      editLabel: "Edit queued message";
      label: "Queued follow-ups";
      moreActions: "More queue actions";
      save: "Save";
      sendNow: "Send now";
      status: "Queued";
      steer: "Steer";
    };
    rateLimits: {
      credits: "Usage credits";
      creditsValue: "{{used}} of {{limit}}";
      remaining: "{{percent}}% remaining";
      resets: "resets {{reset}}";
      title: "Plan usage limits";
      windows: {
        fiveHour: "5h";
        monthly: "Monthly";
        primary: "Primary";
        secondary: "Secondary";
        weekly: "Weekly";
      };
    };
    reasoning: "Reasoning";
    scriptRun: {
      agentCount: "{{started}}/{{max}} agents";
      agentStatus: {
        cancelled: "Cancelled";
        completed: "Completed";
        failed: "Failed";
        queued: "Queued";
        running: "Running";
      };
      cancel: "Cancel";
      discard: "Discard";
      maxAgents: "Agent limit";
      noAgents: "No agents started yet";
      panelLabel: "Script runs";
      proposalLabel: "Script proposal {{name}}";
      proposalTitle: "Script {{name}}";
      run: "Run";
      showScript: "Show script";
      status: {
        draft: "Awaiting approval";
      };
    };
    system: "System";
    team: {
      cancel: "Cancel";
      dismiss: "Hide team";
      endTeam: "Stop all teammates";
      handle: "Respond";
      label: "Team";
      lead: "Lead";
      needsInput: "Needs input";
      noReply: "No reply yet";
      open: "Open session";
      replyPlaceholder: "Reply to {{name}}…";
      send: "Send";
      status: {
        error: "Error";
        idle: "Idle";
        running: "Running";
        spawning: "Starting";
        stopped: "Stopped";
      };
      stopAllDescription_one: "This stops the {{count}} teammate session and drops its queued messages. Your main session keeps running.";
      stopAllDescription_other: "This stops all {{count}} teammate sessions and drops their queued messages. Your main session keeps running.";
      stopAllTitle: "Stop all teammates?";
      stopMember: "Stop {{name}}";
    };
    thinking: "Thinking";
    toolCalls: {
      command: "Command";
      completed: "Completed";
      copyOutput: "Copy output";
      count_one: "{{count}} call";
      count_other: "{{count}} calls";
      execute: "Run";
      executeDone: "Ran";
      failed: "Failed";
      files: "Files";
      files_one: "{{count}} file";
      files_other: "{{count}} files";
      input: "Input";
      openParentSession: "View parent session";
      openParentSessionNamed: "View {{title}}";
      output: "Output";
      outputLoadError: "Failed to load output: {{message}}";
      outputLoading: "Loading output…";
      pending: "Pending";
      readFile: "Read {{fileName}}{{range}}";
      readFileDone: "Read {{fileName}}{{range}}";
      readFiles: "Read files";
      running: "Running";
      search: "Search";
      searchDone: "Searched";
      showLess: "Show less";
      showMore: "Show more";
      skill: "Use skill";
      skillDone: "Used skill";
      subagent: "Using subagent";
      subagentCompleted: "Subagent completed";
      subagentEmpty: "No subagent messages yet.";
      subagentFailed: "Subagent failed";
      subagentPrompt: "Prompt";
      subagentReadOnly: "This subagent session is read-only.";
      subagentResponse: "Subagent response";
      subagentSession: "Subagent session";
      title: "Tool calls";
      viewRendered: "View rendered";
      viewSource: "View source";
      worktreeSetup: "Prepare worktree";
    };
    turnChanges: {
      added: "added";
      conflict: "Undo blocked: a file changed after this turn.";
      deleted: "deleted";
      editedCount_one: "Edited {{count}} file";
      editedCount_other: "Edited {{count}} files";
      fileCountShort_one: "{{count}} file";
      fileCountShort_other: "{{count}} files";
      fileCount_one: "{{count}} file changed";
      fileCount_other: "{{count}} files changed";
      groupTitle: "Changes";
      kind: {
        binary: "binary";
        document: "document";
        image: "image";
        spreadsheet: "spreadsheet";
        text: "text";
      };
      modified: "modified";
      moreFiles: "+{{count}} more";
      moreFiles_one: "+{{count}} more";
      moreFiles_other: "+{{count}} more";
      notRestorable: "too large to restore";
      partial: "Partial coverage";
      renamed: "renamed";
      restored: "Restored files from this turn.";
      review: "Review";
      showFewerFiles: "Show fewer files";
      showMoreFiles_one: "Show {{count}} more file";
      showMoreFiles_other: "Show {{count}} more files";
      undo: "Undo";
      undoFailed: "Undo failed.";
      undoUnavailable: "Undo is unavailable because a file exceeds the checkpoint size or quota.";
      undone: "Undone";
    };
  };
  browser: {
    actions: {
      back: "Back";
      captureScreenshot: "Capture screenshot";
      clearAnnotations: "Clear all annotations";
      closeTab: "Close {{title}}";
      enterDesignMode: "Enter Design Mode";
      exitDesignMode: "Exit Design Mode";
      forward: "Forward";
      newTab: "New tab";
      reload: "Reload";
      removeAnnotation: "Remove annotation";
      stop: "Stop loading";
    };
    annotations: {
      element: "Element";
      region: "Region {{width}}×{{height}}";
      title: "Annotations ({{count}})";
      title_one: "Annotation ({{count}})";
      title_other: "Annotations ({{count}})";
    };
    placeholder: {
      description: "Enter your dev server URL above to preview your app and use Design Mode to annotate UI elements.";
      title: "Browser Preview";
    };
    states: {
      generating: "Generating…";
      loadError: "Unable to load page";
      loading: "Loading...";
    };
    tabs: {
      address: "Page address";
      htmlPreview: "HTML preview";
      label: "Browser tabs";
    };
    urlPlaceholder: "Enter dev server URL (e.g. http://localhost:3000)";
  };
  chat: {
    composer: {
      placeholder: "Ask anything…";
    };
    detail: {
      empty: {
        noProviderTitle: "Add a model provider to start";
        openProviderSettings: "Open provider settings";
        title: "Send a message to start";
      };
    };
    list: {
      empty: {
        description: "Start a new chat to begin.";
        title: "No conversations yet";
      };
      "new": "New chat";
    };
    message: {
      error: "Request failed";
    };
    sidebar: {
      title: "Chat";
    };
  };
  common: {
    actions: {
      attach: "Attach";
      attachFile: "Attach file";
      back: "Back";
      close: "Close";
      closeFile: "Close file";
      closeSearch: "Close search";
      copyCode: "Copy code";
      decrease: "Decrease";
      increase: "Increase";
      send: "Send";
      stop: "Stop";
    };
    agentDescriptions: {
      claudeCli: "Uses the Claude Agent installed and signed in on this computer";
      claudeCode: "Only uses Anthropic Messages models from cocurdex Providers";
      codex: "Fast code generation";
      opencode: "Open-source alternative";
      pi: "Built-in agent";
    };
    agents: {
      claudeCli: "Claude Agent";
      codex: "Codex";
      opencode: "OpenCode";
      pi: "Pi";
    };
    git: {
      turnFiles_one: "{{count}} file";
      turnFiles_other: "{{count}} files";
    };
    htmlPreview: {
      browserLocation: "HTML previews open in the sidebar browser. Use the globe button to open this preview.";
      code: "Code";
      download: "Download HTML";
      localOnly: "Embedded content only. Scripts run when generation finishes; external resources and network requests are blocked.";
      openInBrowser: "Open in built-in browser";
      preview: "Preview";
      title: "HTML preview";
    };
    jumpToLatest: "Jump to latest";
    jumpToTop: "Jump to top";
    message: {
      showLess: "Show less";
      showMore: "Show more";
    };
    permissions: {
      allowed: "";
      denied: "";
      pending: "";
    };
    states: {
      gitEmptyBranchDescription: "";
      gitEmptyBranchTitle: "";
      gitEmptyCommitDescription: "";
      gitEmptyCommitTitle: "";
      gitEmptyDescription: "";
      gitEmptyStagedDescription: "";
      gitEmptyStagedTitle: "";
      gitEmptyTitle: "";
      gitEmptyTurnDescription: "";
      gitEmptyTurnExpiredDescription: "";
      gitEmptyTurnExpiredTitle: "";
      gitEmptyTurnNoneDescription: "";
      gitEmptyTurnNoneTitle: "";
      gitEmptyTurnTitle: "";
      gitEmptyUnstagedDescription: "";
      gitEmptyUnstagedTitle: "";
      gitErrorDescription: "";
      gitErrorTitle: "";
      gitNotRepoDescription: "";
      gitNotRepoTitle: "";
    };
  };
  editor: {
    actions: {
      addToChat: "Add to Chat";
      chatDockTemporarilyFloating: "Chat is floating while the window is narrow and will dock again when widened. Click to cancel docking.";
      chatDockTitle: "Chat";
      chatFabHint: "Open chat. Drag to move. Hover and click the close icon to hide this button ({{shortcut}} to show again).";
      closeChat: "Close chat";
      closeChatSessions: "Close session list";
      closeEditorPanel: "Close editor panel";
      closeFile: "Close file {{fileName}}";
      detachedChatFabHint: "Show or hide the independent chat window. Drag to reposition this button. Hover and click × to hide the button; {{shortcut}} restores it.";
      dockEditorPanel: "Place panel beside chat";
      edit: "Edit";
      enterEditorFullscreen: "Enter full screen";
      exitEditorFullscreen: "Exit full screen";
      explorer: "Explorer";
      floatEditorPanel: "Float panel over chat";
      goBack: "Go back";
      goForward: "Go forward";
      hideChatFab: "Hide chat button";
      hideChatFabHint: "Hide this button. {{shortcut}} to show it again.";
      openChat: "Open chat";
      openEditorPanel: "Open editor panel";
      pinChatDock: "Pin chat to the side";
      pinChatDockNeedsSpace: "The window is too narrow to dock chat. Widen it and try again.";
      preview: "Preview";
      resizeChat: "Resize chat";
      resizeExplorer: "Resize explorer panel";
      resizeSessionList: "Resize session list";
      showBrowser: "Browser";
      showEditor: "Files";
      showGitChanges: "Git";
      showIssues: "Issues";
      showNotes: "Notes";
      showPdf: "PDF";
      showTerminal: "Terminal";
      toggleChat: "Toggle chat";
      toggleChatSessions: "Toggle session list";
      toggleDetachedChat: "Show or hide the chat window";
      toggleSidebar: "Toggle sidebar";
      unpinChatDock: "Unpin chat";
    };
    breadcrumb: {
      navLabel: "Breadcrumb";
    };
    contextMenu: {
      addToChatReadFailed: "Unable to read this file, so it was not added to chat.";
      addToChatTooLarge: "File is too large to add to chat. Attach a selection instead.";
      copyPath: "Copy Path";
      copyRelativePath: "Copy Relative Path";
      revealInFinder: "Reveal in Finder";
    };
    fileTree: {
      collapseTree: "Collapse workspace tree";
      expandTree: "Expand workspace tree";
      search: "Search files";
      searchPlaceholder: "Search files…";
    };
    git: {
      binaryFile: "Binary file not shown";
      branchLabel: "Branch";
      cancel: "Cancel";
      changeType: {
        added: "Added";
        deleted: "Deleted";
        modified: "Modified";
      };
      checkpointUnavailable: "Turn contents are no longer available";
      commit: "Commit";
      commitAndPush: "Commit and push";
      commitAndPushSuccess: "Committed and pushed";
      commitFailed: "Commit failed";
      commitMessage: "Commit message";
      commitMessagePlaceholder: "Commit message (or generate with the button)…";
      commitOrPush: "Commit or push";
      commitSuccess: "Committed";
      copyPath: "Copy path";
      diffUnavailable: "Diff could not be rendered";
      diffViewSettings: "Diff view settings";
      discard: "Discard";
      discardAll: "Discard all";
      discardAllConfirm_one: "Discard changes in {{count}} visible file? This cannot be undone.";
      discardAllConfirm_other: "Discard changes in {{count}} visible files? This cannot be undone.";
      discardChanges: "Discard changes";
      discardConfirm: "Discard all changes to {{file}}? This cannot be undone.";
      fileCount_one: "{{count}} file";
      fileCount_other: "{{count}} files";
      fileTooLarge: "File too large to diff";
      generateCommitMessage: "Generate commit message";
      generateCommitMessageFailed: "Failed to generate commit message";
      generatingCommitMessage: "Generating commit message…";
      hideFileTree: "Hide file tree";
      includeUnstaged: "Include unstaged changes";
      loadingCommits: "Loading commits…";
      loadingTurns: "Loading turns…";
      noCommits: "No commits yet";
      noMatchingBranches: "No matching branches";
      noTurns: "No turns with file changes";
      push: "Push";
      pushFailed: "Push failed";
      pushSuccess: "Pushed";
      refresh: "Refresh changes";
      scope: {
        branch: "Branch";
        commit: "Committed";
        staged: "Staged";
        turn: "Turn";
        unstaged: "Unstaged";
        working: "Uncommitted";
      };
      scopeMenu: "Diff source";
      searchBranches: "Search branches";
      selectSource: "Source branch";
      selectTarget: "Target branch";
      showFileTree: "Show file tree";
      splitView: "Split view";
      stageAll: "Stage all";
      stageFile: "Stage file";
      switchToListView: "Show files as a list";
      switchToTreeView: "Show files as a tree";
      toggleFullFile: "Show full file";
      toggleWrap: "Toggle line wrap";
      treeSearch: "Filter changed files";
      treeSearchPlaceholder: "Filter files…";
      turnFiles: "{{count}} files";
      turnFiles_one: "{{count}} file";
      turnFiles_other: "{{count}} files";
      unifiedView: "Unified view";
      unstageAll: "Unstage all";
      unstageFile: "Unstage file";
    };
    pdf: {
      addPageBookmark: "Bookmark";
      addToNote: "Add to Note";
      addToNoteFailed: "Could not add the selection to the note.";
      addToNoteNoActiveNote: "Notes storage is not ready. Open Notes once, then try again.";
      addedToNewNote: "Created a note and added the selection";
      addedToNote: "Added to note";
      bookmarkPageLabel: "Page {{page}}";
      bookmarks: "Bookmarks";
      closeMarks: "Close bookmarks and highlights";
      closeOutline: "Close outline";
      closeThumbnails: "Close page thumbnails";
      collapseAll: "Collapse all";
      editorHintDescription: "This is a PDF. Open it in the PDF reader tab to view it.";
      editorHintTitle: "PDF files don't open in the code editor";
      expandAll: "Expand all";
      fitPage: "Fit page";
      fitWidth: "Fit width";
      goToPage: "Go to page";
      highlight: "Highlight";
      highlightColor: {
        blue: "Blue";
        green: "Green";
        pink: "Pink";
        yellow: "Yellow";
      };
      highlightColorGroup: "Highlight color";
      highlightWithColor: "Highlight {{color}}";
      highlights: "Highlights";
      loadErrorDescription: "This PDF could not be opened in the reader.";
      loadErrorTitle: "Unable to open PDF";
      markPageBadge: "p.{{page}}";
      marksEmptyDescription: "Bookmark the current page, or select text and highlight it.";
      marksEmptyTitle: "No bookmarks or highlights yet";
      noPdfDescription: "Open a PDF from the file tree to read it here.";
      noPdfTitle: "No PDF open";
      openInReaderAction: "Open in PDF reader";
      outline: "Table of contents";
      pageIndicator: "{{current}} / {{total}}";
      removeBookmark: "Remove bookmark";
      removeHighlight: "Remove highlight";
      removePageBookmark: "Unbookmark";
      resetZoom: "Actual size";
      resizeSidePanel: "Resize PDF side panel";
      search: "Search document";
      searchClose: "Close search";
      searchMatches: "{{current}} / {{total}}";
      searchNext: "Next match";
      searchNoResults: "No results";
      searchPrevious: "Previous match";
      thumbnailError: "—";
      thumbnailLoading: "…";
      thumbnailPage: "Go to page {{page}}";
      thumbnails: "Page thumbnails";
      toggleMarks: "Marks";
      toggleOutline: "Outline";
      toggleSearch: "Search";
      toggleThumbnails: "Thumbnails";
      zoomIn: "Zoom in";
      zoomOut: "Zoom out";
    };
    preview: {
      toc: "Table of contents";
    };
    states: {
      fileReadError: "Unable to read this file in the editor preview.";
      filesLoadError: "Failed to load workspace files.";
      gitEmptyBranchDescription: "The selected branches have no differing files, or one of the refs could not be resolved.";
      gitEmptyBranchTitle: "No branch differences";
      gitEmptyCommitDescription: "This commit did not change any files.";
      gitEmptyCommitTitle: "No changes in commit";
      gitEmptyDescription: "The current workspace has no tracked file changes.";
      gitEmptyStagedDescription: "Nothing is staged yet. Stage files from the working tree to review them here.";
      gitEmptyStagedTitle: "No staged changes";
      gitEmptyTitle: "No git changes";
      gitEmptyTurnDescription: "This turn has no captured file snapshot.";
      gitEmptyTurnExpiredDescription: "The snapshot for this turn has expired and can no longer be reviewed.";
      gitEmptyTurnExpiredTitle: "Turn snapshot expired";
      gitEmptyTurnNoneDescription: "This session has no captured file changes yet.";
      gitEmptyTurnNoneTitle: "No turns";
      gitEmptyTurnTitle: "No turn snapshot";
      gitEmptyUnstagedDescription: "All tracked changes are staged, and there are no untracked files.";
      gitEmptyUnstagedTitle: "No unstaged changes";
      gitErrorDescription: "Git could not read this workspace. Check that git is installed and the repository is intact, then refresh.";
      gitErrorTitle: "Unable to load git changes";
      gitNotRepoDescription: "The current workspace folder is not inside a git repository.";
      gitNotRepoTitle: "Not a git repository";
      loadingFile: "Loading file...";
      loadingGitChanges: "Loading git changes...";
      noFileDescription: "Select a file from the explorer to preview it in the editor area.";
      noFileSelected: "No file selected";
      noWorkspace: "No workspace";
      noWorkspaceDescription: "Select a workspace to inspect git changes.";
      noWorkspaceEditorDescription: "Open a workspace to browse and edit files.";
      noWorkspaceFilesDescription: "Select a workspace to browse files.";
      noWorkspaceTitle: "No workspace selected";
    };
    terminal: {
      closeTab: "Close terminal {{index}}";
      failedToStart: "Failed to start terminal";
      newTab: "New terminal";
      restart: "Restart";
      searchClose: "Close search";
      searchNext: "Next match";
      searchPlaceholder: "Find in terminal";
      searchPrevious: "Previous match";
      selectTab: "Show terminal {{index}}";
      starting: "Starting terminal…";
      tabLabel: "Terminal {{index}}";
    };
  };
  issues: {
    activity: {
      actor: {
        cli: "CLI";
        session: "Agent session";
        user: "You";
      };
      changedField: "changed {{field}}";
      changedFieldTo: "set {{field}} to {{value}}";
      comment: "Comment";
      commentPlaceholder: "Leave a comment…";
      commented: "commented";
      created: "created the issue";
      field: {
        description: "description";
        labels: "labels";
        parent: "parent";
        priority: "priority";
        status: "status";
        title: "title";
        workspace: "workspace";
      };
      none: "none";
      relationAdded: "linked {{issue}}";
      relationRemoved: "unlinked {{issue}}";
      sessionLinked: "linked an agent session";
      title: "Activity";
    };
    board: {
      addCard: "Add card";
      addColumn: "Add column";
      columnMenu: "Column menu";
      columnsField: "Columns";
      columnsFieldHint: "Columns follow this issue field. Drag a card to update the field.";
      deleteCard: "Delete card";
      deleteColumn: "Delete column";
      deleteColumnConfirm: {
        cancel: "Cancel";
        confirm: "Delete";
        description: '"{{title}}" will be removed from this view. Issues keep their field values.';
        title: "Delete column?";
      };
      displayOptions: "View display";
      displayOptionsHint: "Layout and grouping apply only to this view.";
      dragCard: "Drag card";
      dragColumn: "Drag column";
      groupBy: "Grouping";
      groupByHint: "Rows are grouped by this issue field.";
      groupByPriority: "Priority";
      groupByStatus: "Status";
      layout: "Layout";
      layoutBoard: "Board";
      layoutList: "List";
      renameColumnPrompt: "Column name";
      untitledBoard: "Untitled view";
      untitledCard: "Untitled card";
      untitledColumn: "Untitled column";
    };
    cardMenu: {
      delete: "Delete";
      open: "Open";
      priority: "Priority";
      status: "Status";
    };
    category: {
      backlog: "Backlog";
      canceled: "Canceled";
      completed: "Completed";
      started: "Started";
      title: "Status category";
      unstarted: "Unstarted";
    };
    detail: {
      addRelation: "Add relation";
      addSubIssue: "Add sub-issue";
      relation: {
        blockedBy: "Blocked by";
        blocks: "Blocks";
        duplicateOf: "Duplicate of";
        duplicatedBy: "Duplicated by";
        related: "Related to";
      };
      relations: "Relations";
      removeRelation: "Remove relation";
      sessions: "Agent sessions";
      subIssues: "Sub-issues";
      untitledSession: "Untitled session";
    };
    dialog: {
      cancel: "Cancel";
      createIssue: "Create issue";
      descriptionPlaceholder: "Add description…";
      editCard: "Edit issue";
      labels: "Labels";
      loadFailed: "Couldn't load the full description. Close and reopen the issue to edit it.";
      newIssue: "New issue";
      newLabel: "New label";
      newLabelPlaceholder: "Label name";
      noMatchingIssues: "No matching issues";
      noParent: "No parent";
      noWorkspace: "No workspace";
      parent: "Parent";
      priority: "Priority";
      save: "Save";
      searchIssues: "Search issues…";
      status: "Status";
      titlePlaceholder: "Issue title";
      unknownWorkspace: "Unknown workspace";
      workspace: "Workspace";
    };
    empty: {
      description: "Create a card or column to start organizing work.";
      title: "No view yet";
    };
    errors: {
      conflict: "This issue changed elsewhere. The board has been refreshed; please reapply your edit.";
      saveFailed: "Couldn't save the issue change. The board has been refreshed.";
    };
    filter: {
      allLabels: "All labels";
      allWorkspaces: "All workspaces";
      ariaLabel: "Filter view";
      hideClosed: "Hide completed and canceled";
      label: "Label";
      noWorkspace: "No workspace";
      workspace: "Workspace";
    };
    list: {
      collapseGroup: "Collapse {{title}}";
      createdOn: "Created on {{date}}";
      expandGroup: "Expand {{title}}";
      updatedOn: "Updated on {{date}}";
    };
    scope: {
      private: "Private";
      workspace: "{{name}}";
      workspaceFallback: "Workspace";
    };
    sidebar: {
      addBoard: "Add view";
      collapse: "Collapse sidebar";
      deleteView: "Delete view";
      deleteViewConfirm: {
        cancel: "Cancel";
        confirm: "Delete";
        description: 'Delete view "{{title}}"? Issues are shared and will not be deleted.';
        title: "Delete view?";
      };
      expand: "Expand sidebar";
      hint: "Issues and views are stored privately by cocurdex.";
      nav: {
        active: "Active";
        agent: "Agent working";
        all: "All issues";
        backlog: "Backlog";
        title: "Issues";
      };
      newBoardTitle: "New view";
      renameBoard: "Rename view";
      resize: "Resize sidebar";
      title: "View";
      untitledBoard: "Untitled view";
      views: "Views";
    };
  };
  notes: {
    editor: {
      empty: {
        description: "Select a note from the sidebar or create a new one.";
        title: "No note selected";
      };
      folder: {
        description: "Create a note inside from the sidebar, or rename this folder with the title above.";
        emptyTitle: "Folder";
        renameLabel: "Folder name";
      };
      placeholder: 'Start writing, or press "/" for commands…';
      save: {
        error: "Save failed";
        saved: "Saved";
        saving: "Saving…";
      };
      untitledPlaceholder: "Untitled";
    };
    scope: {
      private: "Private";
      workspace: "{{name}}";
      workspaceFallback: "Workspace";
    };
    sidebar: {
      collapse: "Collapse sidebar";
      collapsePage: "Collapse subpages";
      delete: "Delete";
      deleteConfirm: {
        cancel: "Cancel";
        confirm: "Delete";
        descriptionNote: "This note will be permanently deleted.";
        descriptionTree: "This page and all of its subpages will be permanently deleted.";
        title: 'Delete "{{title}}"?';
      };
      empty: {
        description: "Create your first note to start writing.";
        title: "No notes yet";
      };
      expand: "Expand sidebar";
      expandPage: "Expand subpages";
      moveTo: "Move to";
      newNote: "New note";
      newPageInSection: "New page in {{section}}";
      newSubpage: "New subpage";
      rename: "Rename";
      resize: "Resize sidebar";
      sections: {
        personal: "Personal";
      };
      title: "Notes";
      untitled: "Untitled";
    };
    slash: {
      empty: "No matching blocks";
      items: {
        blockquote: "Quote";
        bulletList: "Bulleted list";
        codeBlock: "Code block";
        divider: "Divider";
        heading1: "Heading 1";
        heading2: "Heading 2";
        heading3: "Heading 3";
        orderedList: "Numbered list";
        paragraph: "Text";
        taskList: "To-do list";
      };
    };
  };
  onboarding: {
    action: {
      configureProviders: "Configure providers";
      dontShowAgain: "Don't show this again";
      enterApp: "Go to cocurdex";
      openFolder: "Open a folder";
      openFolderHint: "Agents run inside the folder you pick. This is the main way to use cocurdex.";
      skip: "Skip";
      startChat: "Go to chat";
    };
    description: "cocurdex runs coding agents against a local folder. Here is what is available on this machine.";
    providers: {
      description: "Add a provider and enable the models you want. The built-in pi agent needs one; the other agent CLIs bring their own.";
      title: "Configure a model provider";
    };
    title: "Welcome to cocurdex";
  };
  search: {
    categories: {
      all: "All";
      files: "Files";
      issues: "Issues";
      notes: "Notes";
      sessions: "Sessions";
    };
    categoriesLabel: "Search categories";
    empty: {
      documentsError: {
        description: "Notes and issues could not be searched.";
        title: "Search failed";
      };
      error: {
        description: "ripgrep could not list files for this workspace.";
        title: "Unable to index files";
      };
      loading: {
        description: "Results will appear in a moment.";
        title: "Searching...";
      };
      noFiles: {
        description: "The workspace did not return any searchable files.";
        title: "No files found";
      };
      noMatches: {
        description: "Try a different keyword or category.";
        title: "No results";
      };
      noWorkspace: {
        description: "Open a workspace before searching files.";
        title: "No workspace selected";
      };
      typeToSearch: {
        description: "Search notes and issues by title or content.";
        title: "Type to search";
      };
    };
    files: "Files";
    fullText: {
      caseSensitive: "Match case";
      clearResults: "Clear search results";
      collapseAll: "Collapse all";
      emptyQueryDescription: "Search across the current workspace by file contents.";
      emptyQueryTitle: "Search file contents";
      error: "Error";
      errorDescription: "ripgrep could not complete this search.";
      errorTitle: "Search failed";
      expandAll: "Expand all";
      fileMatchCount_one: "{{count}} match";
      fileMatchCount_other: "{{count}} matches";
      filesToExclude: "files to exclude";
      filesToInclude: "files to include";
      globPlaceholder: "e.g. *.ts, src/**, .claude";
      inputLabel: "Search file contents";
      matchCount_one: "{{count}} match";
      matchCount_other: "{{count}} matches";
      noMatchesDescription: "Try a different term or change the search options.";
      noMatchesTitle: "No text matches";
      placeholder: "Search file contents...";
      resultsInFiles_one: "{{count}} result in {{fileCount}} files";
      resultsInFiles_other: "{{count}} results in {{fileCount}} files";
      searching: "Searching...";
      toggleFilters: "Toggle search details";
      useRegex: "Use regular expression";
      wholeWord: "Match whole word";
    };
    headings: {
      all: "All files";
      recent: "Recently opened";
      recentSessions: "Recent sessions";
      results: "Results";
    };
    hints: {
      changeCategory: "{{previous}} {{next}} Change category";
      open: "↵ Open";
      select: "↑↓ Select";
    };
    more: "More";
    openSearch: "Open search";
    placeholder: "Search sessions, files, notes, issues...";
    searchFiles: "Search files";
    title: "Search";
  };
  sessions: {
    agentRole: {
      avatar: {
        change: "Change avatar";
        color: "Color";
        custom: "Custom emoji";
        customPlaceholder: "Paste or type any emoji";
        groups: {
          animals: "Animals";
          people: "People";
          symbols: "Symbols";
          work: "Work";
        };
        reset: "Use initial";
      };
      cancel: "Cancel";
      description: "Description";
      descriptionPlaceholder: "What this role does and what it is good at. Team leads use it to pick teammates.";
      empty: "No saved roles";
      menuCreate: "New role";
      menuLabel: "Roles";
      menuManage: "Manage roles";
      name: "Name";
      namePlaceholder: "Role name";
      save: "Save as role";
      saveAction: "Save";
      saveDescription: "Name this combination of agent, model, and runtime options.";
      saveFailed: "Could not save this role.";
      saveTitle: "Save as role";
      saved: "Role saved";
    };
    agentSelect: {
      add: "Add from ACP Registry";
      manage: "Manage agent CLIs";
    };
    archive: {
      failed: "Could not archive this session. Try again.";
      success: "Session archived";
      view: "View archived";
    };
    branch: {
      branches: "Branches";
      empty: "No matching branches.";
      noBranch: "No branch";
      searchPlaceholder: "Search branches";
      switchFailed: "Could not switch to {{branch}}. Check the working tree and try again.";
    };
    composer: {
      agentStatus: {
        detecting: "Checking…";
        error: "Unavailable";
        notInstalled: "Not installed";
        updateRequired: "Update required";
      };
      attachMenu: {
        empty: "No matches";
        issues: "Issue";
        notes: "Note";
        search: "Search…";
        skills: "Skill";
      };
      contextFileTooLarge: "File is too large. Select a smaller file or attach a selection.";
      noInstalledAgent: "No agent installed";
      placeholder: "Plan, Build, / for skills, @ for context";
      removeAttachment: "Remove attachment";
      selectAgent: "Select agent";
      sendFollowUp: "Send follow-up...";
      sendFollowUpCompact: "Send follow-up";
      thinkingLevel: "Reasoning effort";
      thinkingLevelWithValue: "Reasoning {{level}}";
      thinkingLevels: {
        default: "Default";
        high: "High";
        low: "Low";
        max: "Max";
        medium: "Medium";
        minimal: "Minimal";
        off: "Off";
        ultra: "Ultra";
        xhigh: "XHigh";
      };
      treeOutline: "Tree outline";
    };
    defaultTitle: "New {{agentLabel}} session";
    modelMenu: {
      defaultTag: "Default";
      empty: "No matching models.";
      emptyUnconfigured: "No providers configured yet.";
      fastMode: "Fast Mode";
      fastModeOff: "Off";
      fastModeOn: "On";
      mcp: "MCP";
      mcpNone: "None";
      mcpNoneConfigured: "No MCP servers reported";
      mcpServers: "MCP servers";
      mcpStatuses: {
        connected: "Connected";
        connecting: "Connecting";
        disabled: "Disabled";
        failed: "Failed";
        unknown: "Unknown";
      };
      mcpSummary: "{{connected}}/{{total}} connected";
      openCodeAgent: "Collaboration mode";
      openCodeAgentDefault: "Default";
      openCodeVariant: "Reasoning effort";
      openCodeVariantDefault: "Default";
      openProviderSettings: "Configure providers";
      reasoningEffort: "Reasoning effort";
      searchPlaceholder: "Search models...";
      selectModel: "Select model";
      serviceTierStandard: "Standard";
      signIn: "Sign in to {{agent}}";
      signInFailed: "Sign-in to {{agent}} failed: {{message}}";
      signInWaiting: "Finish sign-in in the browser…";
      speed: "Speed";
      triggerLabel: "Model";
    };
    permissionMode: {
      changedForModel: "{{model}} does not support Auto mode. Switched to Default permissions.";
      "claude-accept-edits": "Accept edits";
      "claude-auto": "Auto mode";
      "claude-bypass-permissions": "Bypass permissions";
      "claude-default": "Default permissions";
      "claude-plan": "Plan";
      "codex-auto": "Auto";
      "codex-full-access": "Full Access";
      "codex-read-only": "Read Only";
      descriptions: {
        "claude-accept-edits": "Applies file edits automatically; still asks for commands";
        "claude-auto": "Claude decides when to ask";
        "claude-bypass-permissions": "Skips every permission prompt";
        "claude-default": "Asks before edits and commands";
        "claude-plan": "Plans only; no edits or commands";
        "codex-auto": "Edits workspace files and runs commands; asks before network or outside edits";
        "codex-full-access": "Never asks; can edit files outside the workspace and reach the network";
        "codex-read-only": "Reads workspace files; asks before edits or network access";
        "grok-always-approve": "Approves every tool call automatically";
        "grok-ask": "Asks before every tool call";
        "grok-auto": "Grok decides when to ask";
        "opencode-allow": "Approves every tool call automatically";
        "opencode-ask": "Asks before every tool call";
        "opencode-deny": "Rejects every tool call that needs permission";
      };
      "grok-always-approve": "Approve all";
      "grok-ask": "Ask each time";
      "grok-auto": "Auto decide";
      label: "Permission mode";
      "opencode-allow": "Allow";
      "opencode-ask": "Ask";
      "opencode-deny": "Deny";
      unavailableForModel: "{{model}} does not support this mode.";
    };
    sessionMode: {
      "claude-agent": {
        default: "Default";
        plan: "Plan";
      };
      codex: {
        default: "Default";
        plan: "Plan";
      };
      descriptions: {
        "claude-agent": {
          default: "Writes and edits code";
          plan: "Plans changes before implementing";
        };
        codex: {
          default: "Writes and edits code";
          plan: "Plans changes before implementing";
        };
        devin: {
          "accept-edits": "Applies file edits automatically";
          ask: "Answers questions without code changes";
          autonomous: "Sandbox-enforced autonomous agent";
          bypass: "Auto-approves every tool call";
          normal: "Writes and edits code";
          plan: "Plans changes before implementing";
          smart: "Auto-approves the actions the model judges safe";
        };
        "grok-build": {
          default: "Writes and edits code";
          plan: "Plans changes before implementing";
        };
        opencode: {
          default: "Writes and edits code";
          plan: "Plans changes before implementing";
        };
      };
      devin: {
        "accept-edits": "Accept Edits";
        ask: "Ask";
        autonomous: "Autonomous";
        bypass: "Bypass Permissions";
        normal: "Code";
        plan: "Plan";
        smart: "Smart";
      };
      "grok-build": {
        default: "Default";
        plan: "Plan";
      };
      label: "Mode";
      opencode: {
        default: "Default";
        plan: "Plan";
      };
    };
    sidebar: {
      addWorkspace: "Add workspace";
      ageDays_one: "{{count}}d";
      ageDays_other: "{{count}}d";
      ageHours_one: "{{count}}h";
      ageHours_other: "{{count}}h";
      ageMinutes_one: "{{count}}m";
      ageMinutes_other: "{{count}}m";
      ageMonths_one: "{{count}}mo";
      ageMonths_other: "{{count}}mo";
      ageNow: "now";
      ageYears_one: "{{count}}y";
      ageYears_other: "{{count}}y";
      archive: "Archive";
      collapseChildren: "Collapse subagent sessions";
      delete: "Delete";
      editWorkspace: "Edit workspace";
      expandChildren: "Expand subagent sessions";
      markUnread: "Mark as unread";
      marketplace: "Marketplace";
      newSession: "New session";
      newSessionInWorkspace: "New session in {{workspaceName}}";
      noAgentsYet: "No sessions yet";
      pendingAttention: "Needs attention";
      removeWorkspace: "Remove";
      rename: "Rename";
      renameSession: "Rename {{title}}";
      revealInFileManager: "Reveal in file manager";
      running: "Running";
      settings: "Settings";
      showLess: "Show less";
      showMore_one: "Show more ({{count}} left)";
      showMore_other: "Show more ({{count}} left)";
      splitDown: "Open Below";
      splitRight: "Open to the Right";
      unread: "Unread";
      view: {
        agentFilter: "Agent";
        archived: "Archived sessions";
        clearAllFilters: "Clear filters";
        clearFilters_one: "Clear filter";
        clearFilters_other: "Clear {{count}} filters";
        collapseAll: "Collapse all";
        environment: {
          local: "Local";
          worktree: "Worktree";
        };
        environmentFilter: "Environment";
        expandAll: "Expand all";
        filtersLabel: "Filters";
        grouping: {
          agent: "Agent";
          status: "Status";
          updated: "Last updated";
          workspace: "Workspace";
        };
        groupingLabel: "Group by";
        markAllRead: "Mark all as read";
        menu: "Group and filter sessions";
        noMatches: "No matching sessions";
        ordering: {
          activity: "Recent activity";
          created: "Created time";
        };
        orderingLabel: "Sort by";
        rootLimit: {
          all: "All";
          count_one: "{{count}} session";
          count_other: "{{count}} sessions";
        };
        rootLimitLabel: "Sessions per group";
        showLabel: "Show";
        showTimestamps: "Show timestamps";
        source: {
          created: "Created here";
          imported: "Imported";
          issue: "From issues";
        };
        sourceFilter: "Source";
        status: {
          attention: "Needs attention";
          error: "Error";
          idle: "Idle";
          running: "Running";
          unread: "Unread";
        };
        statusFilter: "Status";
        updated: {
          older: "Older";
          today: "Today";
          week: "Past 7 days";
          yesterday: "Yesterday";
        };
      };
      workspacesGroup: "Work";
    };
    split: {
      actions: "Actions";
      close: "Close Pane";
      closeAll: "Close All";
      down: "Split Down";
      menu: "Split session";
      newSession: "New session";
      right: "Split Right";
    };
    team: {
      leadMissing: "Its lead role was deleted";
      menuCreate: "New team";
      menuEmpty: "No teams yet";
      menuLabel: "Team";
      menuManage: "Manage teams";
      summary_one: "{{count}} teammate · Led by {{lead}}";
      summary_other: "{{count}} teammates · Led by {{lead}}";
    };
    window: {
      detach: "Open in a separate window";
      detached: "Chat is open in a separate window";
      retry: "Retry";
      return: "Move back to main window";
      show: "Show chat window";
    };
    workspace: {
      dropFolderDescription: "Release to open it as a workspace.";
      dropFolderTitle: "Drop folder to open";
      editAddFolder: "Add folder";
      editCancel: "Cancel";
      editFoldersLabel: "Source folders";
      editMakePrimary: "Make primary";
      editNameLabel: "Workspace name";
      editPrimary: "Primary";
      editRemoveFolder: "Remove folder";
      editRemoveWorkspace: "Remove workspace";
      editSave: "Save";
      editTitle: "Edit workspace";
      empty: "No matching workspaces.";
      emptyTitle: "Open a workspace to start";
      emptyUnconfigured: "No workspaces yet.";
      enterWorkspace: "Enter workspace";
      home: "Home";
      hostPicker: {
        cancel: "Cancel";
        empty: "No folders here.";
        hideHidden: "Hide hidden folders";
        pathPlaceholder: "Folder path";
        select: "Select this folder";
        showHidden: "Show hidden folders";
        title: "Choose folder";
        up: "Go to parent folder";
      };
      missing: "Folder missing — click to relocate";
      openFolder: "Open Folder";
      openedExisting: "Opened existing workspace “{{name}}”";
      recents: "Recents";
      removeFailed: "Could not remove this workspace. Try again.";
      rootsAdditional: "Additional folders";
      rootsPrimary: "Primary folder";
      startDescription: "Pick a model, describe the task, and keep the first prompt scoped.";
      startTitle: "What should we do in {{workspaceName}}?";
      startTitleAfter: "?";
      startTitleBefore: "What should we do in";
      workspace: "Workspace";
    };
    worktree: {
      createFailed: "Could not create worktree. {{message}}";
      empty: "No matching worktrees.";
      label: "Worktree";
      main: "Main";
      searchPlaceholder: "Search worktrees";
      worktrees: "Worktrees";
    };
  };
  settings: {
    adapters: {
      action: {
        copyCommand: "Copy command";
        copyPath: "Copy path";
        docs: "Docs";
        refresh: "Refresh";
      };
      badge: {
        builtin: "Built in";
        updateRequired: "Update required";
      };
      description: "Pick any of these agent CLIs when starting a session. cocurdex detects the versions installed on this machine; add more from the ACP Registry.";
      kind: {
        builtin: "Built-in";
        detecting: "Checking…";
        error: "Failed";
        missing: "Not installed";
        outdated: "Update required";
        ready: "Ready";
      };
      rateLimits: {
        authenticationRequired: "No usage found. Not signed in. Run claude auth login, then refresh.";
        failed: "Could not read usage: {{message}}";
        loading: "Loading usage…";
        timedOut: "Usage check timed out. Try refreshing.";
        unknownError: "Unknown error";
      };
      registry: {
        builtIn: "Built in";
        description: "Install coding agents published to the official ACP Registry. They are third-party code: review an agent's source and license before installing it.";
        install: "Install";
        installFailed: "Installation failed";
        installSucceeded: "Installed {{name}}";
        installed: "Installed";
        loadFailed: "Could not load the ACP Registry";
        manual: {
          args: "Arguments";
          back: "Back";
          command: "Command";
          description: "Install the agent yourself first, then enter its executable name or absolute path and the arguments that start ACP mode.";
          open: "Use my own command";
          save: "Save";
        };
        noResults: "No matching agents";
        open: "Add from ACP Registry";
        plan: {
          cancel: "Cancel";
          confirm: "Install";
          copied: "Command copied";
          copy: "Copy command";
          directory: "Install to";
          download: "Download";
          launch: "Launch command";
          localNote: "Found this CLI on your machine. Nothing will be downloaded; the agent runs it directly.";
          noChecksum: "The registry provides no checksum, so the download cannot be verified.";
          packageNote: "Installing runs {{runner}} once to download this pinned package version into its local cache. Later starts reuse the cache.";
          prefetch: "Runs during install";
        };
        remove: "Remove";
        removeFailed: "Could not remove the agent";
        removeSucceeded: "Removed {{name}}";
        retry: "Retry";
        search: "Search agents";
        title: "ACP Registry";
        unsupported: "Not available for this platform";
      };
      status: {
        builtin: "Built in — ships with cocurdex, nothing to install.";
        detecting: "Checking installation…";
        error: "Detection failed.";
        missing: "Not installed — {{executable}} was not found on PATH.";
        outdated: "Installed {{installed}} is below the required {{minimum}}.";
        outdatedHint: "Still usable. Some capabilities may not work until you update.";
        ready: "Installed and ready.";
      };
      toast: {
        commandCopied: "Install command copied";
        pathCopied: "Path copied";
        refreshFailed: "Could not refresh agent CLIs";
      };
    };
    agentRoles: {
      cancel: "Cancel";
      create: "New role";
      createTitle: "New role";
      delete: "Delete";
      deleteDescription: '"{{name}}" will be removed. This cannot be undone.';
      deleteFailed: "Could not delete this role.";
      deleteTitle: "Delete this role?";
      deleted: "Role deleted";
      description: "Manage saved roles. Save one from the composer model menu, then edit it here.";
      edit: "Edit";
      editTitle: "Edit role";
      empty: "No roles yet";
      emptyDescription: "Click New role, or choose Save as role from the model menu when starting a session.";
      listTitle: "Saved roles";
      name: "Name";
      namePlaceholder: "Role name";
      roleDescription: "Description";
      roleDescriptionPlaceholder: "What this role does and what it is good at. Team leads use it to pick teammates.";
      runtime: "Agent and model";
      save: "Save";
      saveFailed: "Could not save this role.";
      saved: "Role updated";
    };
    appearance: {
      groupTitle: "Appearance";
      modes: {
        dark: "Dark";
        light: "Light";
        system: "System";
      };
      preset: {
        description: "Color palette applied to both light and dark modes. cocurdex is the default product look.";
        empty: "No themes found";
        searchPlaceholder: "Search themes...";
        title: "Color theme";
      };
      theme: {
        description: "Choose between light, dark, or system themes.";
        title: "Theme";
      };
      typography: {
        codeFontFamily: {
          description: "Font used in code editors and diffs.";
          system: "System monospace";
          title: "Code font family";
        };
        codeFontSize: {
          description: "Font size for code editors and diffs.";
          title: "Code font size";
        };
        fontEmpty: "No fonts found";
        fontSearchPlaceholder: "Search fonts...";
        groupTitle: "Typography";
        uiFontFamily: {
          description: "Font used across the application interface.";
          system: "System font";
          title: "UI font family";
        };
        uiFontSize: {
          description: "Base font size for the application interface.";
          title: "UI font size";
        };
      };
    };
    archive: {
      archivedOn: "Archived {{date}}";
      deleteConfirm: {
        cancel: "Cancel";
        confirm: "Delete";
        description: "This permanently removes the session and its sub-sessions from this device. This cannot be undone.";
        title: "Delete “{{title}}”?";
      };
      deleteFailed: "Could not delete this session. Try again.";
      deleteNamed: "Delete {{title}}";
      deleted: "Session deleted";
      description: "Archived sessions stay on this device. Restore a session to return it to the sidebar, together with sub-sessions archived with it.";
      empty: "No archived sessions";
      loadFailed: "Could not load archived sessions";
      loading: "Loading archived sessions…";
      noResults: "No matching sessions";
      restore: "Restore";
      restoreFailed: "Could not restore this session. Try again.";
      restoreNamed: "Restore {{title}}";
      restored: "Session restored to the sidebar";
      retry: "Retry";
      search: "Search by session, workspace, or agent";
    };
    assistant: {
      close: "Close assistant";
      loading: "Starting assistant…";
      newSession: "New assistant session";
      noWorkspace: "Add a workspace to chat with the assistant.";
      open: "Open assistant";
      prompts: {
        chatDisplay: "Show me the chat display options and help me pick one using the settings tools.";
        explore: "List the Cocurdex settings you can inspect or change with the settings tools, and briefly tell me what you can help with.";
        language: "Help me switch the interface language using the settings tools.";
        notifications: "Review my notification settings and adjust them using the settings tools.";
        theme: "Switch the app theme to dark mode using the settings tools.";
      };
      suggestions: {
        chatDisplay: "Change chat display";
        explore: "What can you change?";
        language: "Switch language";
        notifications: "Adjust notifications";
        theme: "Switch to dark theme";
        worktree: "Suggest worktree scripts";
      };
      title: "Assistant";
      worktreeKickoff: "Inspect this repository and propose worktree setup and cleanup scripts for it. Suggest both and leave neither empty: setup installs dependencies and generates code, cleanup removes build caches, temp directories, or processes before the worktree is recycled. Review the repository files, then submit your recommendation with the settings_propose tool so I can approve it.";
    };
    chatDisplay: {
      activity: {
        description: "Concise shows only final replies; Standard folds reasoning, tool calls, and interim replies into a summary; Verbose expands everything.";
        options: {
          condensed: "Standard";
          expanded: "Verbose";
          hidden: "Concise";
        };
        title: "Transcript view";
      };
      groupTitle: "Conversation display";
      hideFab: {
        description: "When chat is closed in floating or pinned layout, hide the bottom-right button. Open chat again with {{shortcut}}.";
        title: "Hide chat button when closed";
      };
      htmlPreview: {
        description: "Choose where HTML is previewed as it is generated.";
        options: {
          browser: "Sidebar browser";
          chat: "Chat area";
        };
        title: "HTML preview location";
      };
      layout: {
        description: "How chat sits relative to the editor. Restored on next launch.";
        options: {
          center: "Center column";
          float: "Floating dock";
          pinned: "Pinned right rail";
        };
        title: "Chat layout";
      };
    };
    cli: {
      actions: {
        install: "Install";
        refresh: "Refresh";
        reinstall: "Repair";
        uninstall: "Uninstall";
      };
      description: "Install the cocurdex command so terminals and agents can call the CLI.";
      groupTitle: "Command line";
      loading: "Checking CLI install…";
      status: {
        foreignInstall: "Another cocurdex command exists at {{path}}. Repair to point it at this app.";
        installedNotOnPath: "Installed at {{path}}, but that folder is not on PATH. Open a new terminal or add it to PATH.";
        notInstalled: "The cocurdex command is not installed for this user.";
        ready: "Ready. Terminals can run cocurdex ({{path}}).";
      };
      title: "Shell command";
      toast: {
        installFailed: "Could not install the cocurdex command";
        installed: "cocurdex command installed";
        uninstallFailed: "Could not uninstall the cocurdex command";
        uninstalled: "cocurdex command removed";
      };
    };
    daemon: {
      actions: {
        refresh: "Check status";
        restart: "Restart";
        start: "Start";
      };
      description: "The local cocurdex daemon holds the app database and agent sessions. Restart it if notes, issues, or agents stop responding.";
      details: {
        protocol: "Protocol version {{version}}";
        runtime: "Runtime {{fingerprint}}";
        socket: "Socket {{path}}";
        startedAt: "Started {{value}}";
      };
      groupTitle: "Daemon";
      loading: "Checking daemon status…";
      status: {
        outdated: "Running (pid {{pid}}), but the runtime does not match this app. Restart to replace it.";
        running: "Running (pid {{pid}}).";
        runningOwned: "Running (pid {{pid}}), managed by this app.";
        stopped: "Not running. Start or restart to bring it back.";
      };
      title: "Local daemon";
      toast: {
        restartFailed: "Could not restart the daemon";
        restarted: "Daemon restarted";
      };
    };
    diagnostics: {
      actions: {
        export: "Export Diagnostics…";
      };
      description: "Bundle sanitized app logs and runtime info for troubleshooting.";
      group: "Logs";
      status: {
        exported: "Exported to {{path}}";
        failed: "Export failed: {{message}}";
      };
      title: "Export diagnostics";
      verbose: {
        description: "Record verbose diagnostic details in app logs. Logs stay sanitized either way.";
        title: "Verbose diagnostics";
      };
    };
    editor: {
      minimap: {
        description: "Show a miniature overview of the current file along the editor edge.";
        title: "Code MiniMap";
      };
    };
    followUp: {
      description: "Queue follow-ups until the current run finishes, or steer an active run when supported. Press {{shortcut}} to use the opposite behavior for one message.";
      groupTitle: "Agent behavior";
      options: {
        queue: "Queue";
        steer: "Steer";
      };
      title: "Follow-up behavior";
    };
    git: {
      commitMessageModel: {
        agentDescription: "Agent used to generate Git commit messages.";
        agentLabel: "Agent";
        footnote: "When the commit message is left blank, the selected model generates a Conventional Commits subject from the staged changes. If no model is set, you must type a message yourself.";
        group: "Commit messages";
        modelDescription: "Model used to generate Git commit messages.";
        modelLabel: "Model";
        noModels: "No compatible models";
        none: "None (type message manually)";
        saveFailed: "Failed to update commit message model";
      };
    };
    groups: {
      agent: "Agent";
      interface: "Interface";
      system: "System";
      workspace: "Workspace";
    };
    language: {
      description: "Choose the interface language used by product UI.";
      empty: "No languages found";
      groupTitle: "Language";
      modes: {
        system: "System";
      };
      searchPlaceholder: "Search languages...";
      title: "Interface language";
    };
    licenses: {
      chromiumDescription: "Chromium and Electron third-party notices are kept in a separate credits file shipped with the app.";
      chromiumOpen: "Open Chromium licenses";
      chromiumTitle: "Chromium / Electron";
      chromiumUnavailable: "Chromium license file is not available in this build.";
      description: "Third-party notices for bundled dependencies";
      dialogDescription: "License texts for software bundled with Cocurdex.";
      dialogTitle: "Open source licenses";
      empty: "Try a different name, license, or version.";
      emptyTitle: "No matching packages";
      loadError: "The bundled license catalog could not be read.";
      loadErrorTitle: "Could not load licenses";
      loading: "Loading licenses…";
      noLicenseText: "No license text was bundled for this package.";
      packageCount: "{{total}} packages";
      packageCountFiltered: "{{visible}} of {{total}}";
      retry: "Retry";
      searchPlaceholder: "Search packages";
      title: "Open source licenses";
      view: "View";
    };
    mcp: {
      description: 'Configure the MCP servers available to the built-in Pi agent. Pi connects to them when a session starts. Server names may contain only letters, digits, "_", and "-".';
      editorLabel: "MCP server configuration";
      form: {
        add: "Add server";
        arguments: "Arguments";
        argumentsDescription: "Enter one argument per line.";
        argumentsPlaceholder: "-y\npackage-name";
        command: "Command";
        commandPlaceholder: "npx";
        emptyDescription: "Add a local command or remote endpoint to make its tools available to Pi.";
        emptyTitle: "No MCP servers configured";
        environment: "Environment variables";
        environmentDescription: "Enter one KEY=value pair per line.";
        environmentPlaceholder: "API_KEY=${API_KEY}";
        local: "Local";
        name: "Server name";
        namePlaceholder: "github";
        remote: "Remote";
        remove: "Remove server";
        servers: "Servers";
        transport: "Connection";
        url: "Server URL";
        urlPlaceholder: "https://example.com/mcp";
      };
      mode: {
        form: "Form";
        json: "JSON";
        label: "Configuration mode";
      };
      restartHint: "Changes apply when a Pi session starts. Existing running sessions keep their current tools.";
      save: "Save";
      saved: "MCP configuration saved";
      saving: "Saving";
      title: "MCP";
    };
    network: {
      proxy: {
        allProxy: {
          description: "Optional catch-all proxy (ALL_PROXY), for example socks5://127.0.0.1:1080. Agent CLIs may use this when HTTP/HTTPS proxies are unset.";
          placeholder: "socks5://127.0.0.1:1080";
          title: "All / SOCKS proxy";
        };
        credentialsNote: "Proxy URLs are stored as plain text in app settings and are passed to Agent subprocesses. Avoid embedding credentials you would not want a spawned CLI to read.";
        groupTitle: "Network proxy";
        httpProxy: {
          description: "HTTP proxy URL. Example: http://127.0.0.1:7890 or http://user:pass@host:port.";
          placeholder: "http://127.0.0.1:7890";
          title: "HTTP proxy";
        };
        httpsProxy: {
          description: "HTTPS proxy URL. Leave empty to reuse the HTTP proxy.";
          placeholder: "Same as HTTP proxy";
          title: "HTTPS proxy";
        };
        invalidUrl: "{{field}} must be a full URL with a scheme, e.g. http://127.0.0.1:7890";
        loading: "Loading proxy settings…";
        manualGroupTitle: "Manual proxy";
        manualIncomplete: "Manual mode is selected but no proxy address is set, so traffic still goes direct.";
        modeTitle: "Proxy mode";
        modes: {
          manual: "Manual";
          off: "Off";
          system: "System / environment";
        };
        noProxy: {
          description: "Comma-separated hosts that bypass the proxy. Localhost is recommended so app IPC stays direct.";
          placeholder: "localhost,127.0.0.1,::1,.local";
          title: "Bypass list (NO_PROXY)";
        };
        notesBody: "Applies to Agent subprocesses (including ACP), app and daemon model/API requests, and Chromium network traffic. Does not change your system proxy or force the integrated terminal to use these settings. Restart an active agent session after changing proxy settings so the new environment is picked up.";
        notesGroupTitle: "Scope";
        saveFailed: "Failed to save proxy settings";
        scopeDescription: "Used for Agents and app outbound network requests. Does not hijack the system proxy or the integrated terminal by default.";
        status: {
          checking: "Checking connectivity…";
          idle: "Hover to check connectivity";
          label: "Proxy status";
          offDetail: "Outbound traffic is direct; no app proxy is applied.";
          openSettings: "Open network settings";
        };
        test: {
          action: "Test";
          description: "Sends one request to ipinfo.io through the app's outbound path and reports the egress address, so you can tell whether the proxy is really in use.";
          failure: "Failed: {{error}}";
          success: "Reachable in {{durationMs}} ms — egress IP {{ip}}";
          title: "Test connectivity";
          unknownIp: "unknown";
        };
      };
    };
    notifications: {
      completed: {
        body: "An agent run has completed.";
        title: "Agent finished";
      };
      completionSound: {
        description: "Play a sound when an agent finishes responding.";
        title: "Completion sound";
      };
      groupTitle: "Notifications";
      permission: {
        body: "An agent is waiting for permission approval.";
        title: "Approval needed";
      };
      question: {
        body: "An agent is waiting for your answer.";
        title: "Agent needs input";
      };
      systemNotifications: {
        description: "Show a system notification when an agent finishes or needs your attention.";
        title: "System notifications";
      };
    };
    placeholder: {
      description: "This group is reserved as a placeholder. Add concrete fields and interactions after the information architecture is settled.";
      title: "{{section}} placeholder";
    };
    providers: {
      actions: {
        add: "Add";
        clearKey: "Clear key";
        delete: "Delete";
        importJson: "Import JSON";
        newProvider: "New";
        refresh: "Refresh";
        save: "Save";
      };
      auth: {
        accountDescription: "Use a provider account or subscription through Pi OAuth.";
        addProvider: "Add provider";
        apiKeyDescription: "Use an API key managed by Pi.";
        cancel: "Cancel";
        codeCopied: "Code copied";
        connected: "Connected";
        continue: "Continue";
        copyCode: "Copy code";
        deviceCodeHint: "Enter this code in your browser to finish signing in";
        loginFailed: "Unable to authenticate with this provider";
        logoutFailed: "Unable to sign out";
        openBrowser: "Open browser";
        readFailed: "Unable to read provider authentication";
        setApiKey: "Set API key";
        signIn: "Sign in";
        signOut: "Sign out";
        source: {
          ambient: "From {{source}}";
          oauth: "OAuth";
          stored: "Stored key";
        };
        starting: "Starting authentication…";
        title: "Authentication";
        waitingForBrowser: "Waiting for browser…";
      };
      deleteConfirm: {
        cancel: "Cancel";
        confirm: "Delete";
        description: "Delete {{provider}} and all of its models? This cannot be undone.";
        title: "Delete provider";
      };
      details: {
        title: "Provider details";
      };
      empty: {
        noMatches: "No matching providers";
      };
      fields: {
        apiKey: "API key";
        baseUrl: "Base URL";
        capabilities: "Capabilities";
        capability: {
          agent: "Agent";
          chat: "Chat";
          reasoning: "Reasoning";
          vision: "Vision";
        };
        contextLimit: "Context";
        cost: {
          cacheRead: "Cache read";
          cacheWrite: "Cache write";
          input: "Input";
          output: "Output";
          title: "Cost / 1M tokens";
        };
        costJson: 'Cost JSON, e.g. {"input":3,"output":15}';
        displayName: "Display name";
        headersJson: 'Custom headers JSON, e.g. {"x-api-version":"1"}';
        modelCompat: "Compatibility";
        modelCompatHint: "JSON object for adapter-specific compatibility flags";
        modelCompatJson: "Model compatibility JSON";
        modelId: "Model ID";
        modelRuntime: "Model runtime";
        newApiKey: "New API key";
        outputLimit: "Output";
        providerCompatJson: "Provider compatibility JSON";
        providerId: "Provider ID";
        reasoning: "Supports reasoning";
        runtime: {
          "anthropic-messages": "Anthropic Messages";
          "google-generative-ai": "Google Generative AI";
          "mistral-conversations": "Mistral Conversations";
          "openai-codex-responses": "OpenAI Codex Responses";
          "openai-completions": "OpenAI Completions";
          "openai-responses": "OpenAI Responses";
        };
        thinkingLevelMap: "Thinking map";
        thinkingLevelMapHint: 'JSON object mapping levels to token budgets, e.g. {"high":10000}';
        thinkingLevelMapJson: 'Thinking level map JSON, e.g. {"high":10000}';
      };
      header: {
        description: "Configure service endpoints, models, and agent defaults.";
        title: "Provider management";
      };
      importJson: {
        cancel: "Cancel";
        confirm: "Import";
        description: "Import a pi-style models.json. Each provider is upserted with its models. Literal apiKey values are stored; $ENV and !command keys must be set manually.";
        dropActive: "Drop to import";
        dropHint: "Drop a JSON file here, or click to choose one.";
        importing: "Importing…";
        intro: "Add or update providers and models from a pi-style models.json.";
        invalidFile: "Choose a JSON text file.";
        label: "Import providers from JSON";
        providerCount: "{{count}} providers";
        providerCount_one: "{{count}} provider";
        providerCount_other: "{{count}} providers";
        summary: "Will write {{providers}} and {{models}}.";
        title: "Import JSON";
        warnings: {
          authHeaderNoKey: 'Provider "{{id}}": authHeader is set but no literal apiKey was provided.';
          commandApiKey: 'Provider "{{id}}": shell-command apiKey (!…) is not run on import; set the key manually.';
          envApiKey: 'Provider "{{id}}": environment apiKey ($…) is not expanded on import; set the key manually.';
          oauthIgnored: 'Provider "{{id}}": oauth config is ignored on import.';
        };
      };
      list: {
        configuredCount: "{{count}} configured";
      };
      models: {
        addTitle: "Add model";
        advanced: "Advanced";
        authenticateToLoad: "Authenticate above to load this provider's models.";
        columns: {
          capabilities: "Capabilities";
          compat: "Compat";
          cost: "Cost / 1M";
          defaultModel: "Default";
          input: "Input";
          no: "No";
          reasoning: "Reasoning";
          reasoningEfforts: "Reasoning options";
          serviceTiers: "Service tiers";
          thinking: "Thinking map";
          yes: "Yes";
        };
        empty: "No models configured for {{provider}}.";
        modelCount: "{{count}} models";
        modelCount_one: "{{count}} model";
        modelCount_other: "{{count}} models";
        noMatches: "No matching models";
        parametersFor: "{{model}} parameters";
        parametersTitle: "Model parameters";
        runtimeFor: "{{model}} runtime";
        searchPlaceholder: "Search models...";
        showingCount: "Showing {{visible}} of {{total}} models";
        title: "Models";
        toggleFor: "Toggle {{model}}";
      };
      searchPlaceholder: "Search providers...";
      sections: {
        advanced: "Advanced";
        auth: "Auth";
        provider: "Provider";
      };
      select: "Select";
      state: {
        configured: "Configured";
        disabled: "Disabled";
        enabled: "Enabled";
        keySet: "Key set";
        noKey: "No key";
        notConfigured: "Not configured";
      };
      status: {
        deleteFailed: "Unable to delete provider";
        idExists: "Provider ID {{id}} already exists";
        importFailed: "Unable to import providers";
        importSucceeded: "Imported {{count}} provider(s)";
        importSucceeded_one: "";
        importSucceeded_other: "";
        missingFields: "Required fields are missing";
        modelDisabled: "Model disabled";
        modelEnabled: "Model enabled";
        modelSaved: "Model saved";
        modelsRefreshFailed: "Unable to refresh models";
        modelsRefreshed: "Models refreshed";
        providerDeleted: "Provider deleted";
        providerSaved: "Provider saved";
        refreshingModels: "Refreshing models...";
        saveFailed: "Unable to save provider";
      };
      templates: {
        description: "Pick a preset, save it, then choose an available authentication method.";
        title: "Add a provider";
      };
      titleModel: {
        description: "Generates titles for the built-in Pi agent and chat mode. Other agents use their own title support.";
        label: "Pi session title generation model";
        none: "Use current session model";
        probeFailed: "Failed · {{latencyMs}} ms · {{error}}";
        probeOk: "Connected · {{latencyMs}} ms";
        probeOkWithTitle: "Connected · {{latencyMs}} ms · “{{title}}”";
        saveFailed: "Failed to update title model";
        selectModelFirst: "Select a title model first";
        test: "Test";
        testing: "Testing…";
      };
    };
    sections: {
      about: "About";
      adapters: "Agent CLIs";
      agentRoles: "Roles";
      appearance: "Appearance";
      archived: "Archived sessions";
      computer: "Computer use";
      diagnostics: "Diagnostics";
      editor: "Editor";
      environment: "Network";
      general: "General";
      git: "Git";
      licenses: "Open source licenses";
      mcp: "MCP";
      personalization: "Personalization";
      providers: "Providers";
      shortcuts: "Shortcuts";
      skills: "Skills";
      teams: "Teams";
      usage: "Usage";
      workflows: "Workflows";
      workspaces: "Workspaces";
      worktrees: "Worktrees";
    };
    sendShortcut: {
      description: "Choose when Enter sends a prompt or inserts a new line.";
      options: {
        "command-enter": "{{shortcut}} always";
        "command-enter-multiline": "{{shortcut}} for multiline prompts";
        enter: "Enter";
      };
      title: "Send shortcut";
    };
    shortcuts: {
      actions: {
        fileSearch: {
          description: "Open the workspace file search palette.";
          title: "Search files";
        };
        toggleChatDock: {
          description: "Show or hide the floating/pinned chat dock when the editor is fullscreen.";
          title: "Toggle chat dock";
        };
        toggleDesignMode: {
          description: "Toggle browser design annotation mode.";
          title: "Toggle design mode";
        };
        toggleEditorFullscreen: {
          description: "Expand the editor to fullscreen (floating/pinned chat) or return to the center chat layout.";
          title: "Toggle editor fullscreen";
        };
        toggleLeftSidebar: {
          description: "Show or hide the left sidebar.";
          title: "Toggle left sidebar";
        };
        toggleRightPanel: {
          description: "Show or hide the editor panel.";
          title: "Toggle editor panel";
        };
        toggleWorkspaceSearch: {
          description: "Open workspace search in the editor panel.";
          title: "Search in workspace";
        };
      };
      categories: {
        browser: "Browser";
        chat: "Chat";
        editor: "Editor";
        general: "General";
        layout: "Layout";
      };
      conflict: "Conflicts with {{action}}";
      description: "Click a binding to record a new chord. Escape cancels recording; Backspace clears the binding.";
      editBinding: "Edit shortcut {{binding}}";
      emptyDescription: "Try a different name or category.";
      emptyTitle: "No shortcuts match";
      hint: "Shortcuts pause while a binding is being recorded. Changes are saved automatically.";
      recording: "Press keys…";
      reset: "Reset to default";
      resetAll: "Reset all";
      searchPlaceholder: "Search shortcuts…";
      unbound: "None";
    };
    sidebar: {
      resize: "Resize settings sidebar";
    };
    skills: {
      actions: {
        install: "Install";
        refresh: "Refresh";
        reinstall: "Reinstall";
        remove: "Remove";
        update: "Update";
      };
      cliHint: "CLI: cocurdex skills install --scope project|global  ·  cocurdex skills status --scope project|global";
      groupTitle: "Install location";
      intro: "Install cocurdex product skills so agents (Claude, OpenCode, Pi, and others) can run Notes and Issues workflows. Installation is manual — nothing is written until you install.";
      loading: "Checking skill install…";
      scope: {
        global: {
          description: "Install under ~/.agents/skills and ~/.claude/skills for every workspace on this machine.";
          title: "Global (all workspaces)";
        };
        project: {
          description: "Install into the active workspace (.agents/skills and .claude/skills). Good for team repos you commit.";
          title: "This workspace";
        };
      };
      status: {
        conflict: "Unmanaged cocurdex skill folders already exist ({{skills}}). Remove or rename them under {{path}}, then install again.";
        installed: "Installed v{{version}} at {{path}}";
        noWorkspace: "Select a workspace first to install workspace-level skills.";
        notInstalled: "Not installed. Would write to {{path}}";
        updateAvailable: "Installed v{{installed}}; pack v{{latest}} is available at {{path}}";
      };
      toast: {
        alreadyInstalled: "Skills are already up to date";
        conflict: "Could not install: conflict with existing skills ({{skills}})";
        installFailed: "Could not install skills";
        installed: "cocurdex skills installed";
        removeFailed: "Could not remove skills";
        removed: "cocurdex skills removed";
        updated: "cocurdex skills updated";
      };
      workspaceLabel: "Active workspace: {{name}}";
    };
    teams: {
      addMember: "Add teammate";
      backToTeam: "Back to team";
      cancel: "Cancel";
      create: "New team";
      createFirst: "Create one";
      createRole: "New role";
      createTitle: "New team";
      delete: "Delete";
      deleteDescription: '"{{name}}" will be removed. This cannot be undone.';
      deleteFailed: "Could not delete this team.";
      deleteTitle: "Delete this team?";
      deleted: "Team deleted";
      description: "Save team lineups you use often. Pick a team from the agent menu when starting a session; its lead plans the work and spawns teammates from the lineup.";
      edit: "Edit";
      editTitle: "Edit team";
      empty: "No teams yet.";
      lead: "Lead";
      leadAgents: "Agents";
      leadPlaceholder: "Choose a lead";
      leadPromptPlaceholder: "What the lead focuses on while coordinating.";
      leadRoles: "Roles";
      listTitle: "Saved teams";
      makeLead: "Make lead";
      memberCount: "{{current}}/{{max}}";
      memberPrompt: "Standing instructions";
      memberPromptPlaceholder: "What this teammate is responsible for.";
      members: "Teammates";
      membersHint: "The first member is the lead: it runs the session and dispatches the others.";
      name: "Name";
      namePlaceholder: "Team name";
      removeMember: "Remove teammate";
      role: "Role";
      roleMissing: "Role was deleted";
      rolePlaceholder: "Choose a role";
      save: "Save";
      saveFailed: "Could not save this team.";
      saved: "Team saved";
      scriptRuns: {
        defaultMaxAgents: "Default agent limit";
        defaultMaxAgentsDescription: "Maximum agents one script run may start; you can change it when approving";
        description: "Agents in a session can propose background scripts that orchestrate subagents; they run after you approve them";
        maxDuration: "Maximum run time";
        maxDurationDescription: "Cancels the whole run and its subagents when exceeded; leave empty for no limit";
        minutes: "min";
        saveFailed: "Could not save script run settings";
        schemaMaxAttempts: "Structured reply attempts";
        schemaMaxAttemptsDescription: "How many times an agent may try to reply with JSON matching the script's schema";
        title: "Script runs";
        unlimited: "No limit";
      };
      teamDescription: "Description";
      teamDescriptionPlaceholder: "What this team is for. The lead agent reads this to decide when to use it.";
    };
    updates: {
      actions: {
        check: "Check for updates";
        install: "Update and Restart";
      };
      card: {
        body: "Version {{version}} is ready. It will take effect after restart.";
        changelog: "View release notes";
        install: "Update and Restart";
        later: "Later";
        title: "Update available";
      };
      channel: {
        ariaLabel: "Update channel";
        description: "Test builds can be unstable. Switching back to Stable may install an older version.";
        options: {
          stable: "Stable";
          test: "Test";
        };
        title: "Update channel";
      };
      description: "Installed version {{version}}.";
      groupTitle: "App";
      status: {
        checking: "Checking for updates…";
        downloading: "Downloading version {{version}}…";
        downloadingWithPercent: "Downloading version {{version}}… {{percent}}%";
        error: "Could not check for updates. {{message}}";
        ready: "Version {{version}} is downloaded and ready to install.";
        unsupported: "Automatic updates are available in the packaged app.";
        upToDate: "You're up to date.";
      };
      title: "Version";
    };
    workflows: {
      addAgent: "Add agent";
      addGate: "Add gate";
      addTerminal: "Add end";
      artifact: {
        change_set: {
          v1: "";
        };
        "change_set.v1": "Change set";
        plan_artifact: {
          v1: "";
        };
        "plan_artifact.v1": "Plan";
        review_decision: {
          v1: "";
        };
        "review_decision.v1": "Review decision";
        validation_report: {
          v1: "";
        };
        "validation_report.v1": "Validation report";
      };
      bindings: {
        description: "Default planner, implementer, and reviewer roles used when creating a run from this definition.";
        placeholder: "Select a role";
      };
      builtin: "Built in";
      custom: "Custom";
      delete: "Delete";
      description: "Edit a labeled state machine of agent and gate steps. Duplicate the built-in template to change nodes and connections.";
      duplicate: "Duplicate";
      empty: "No workflow definitions yet.";
      inspector: {
        addInput: "Add input";
        edge: "Transition";
        empty: "Select a node or connection.";
        inputs: "Inputs";
        instruction: "Instruction";
        maxAttempts: "Max attempts";
        maxTraversals: "Max traversals";
        output: "Output";
        role: "Role";
      };
      node: {
        agent: "Agent";
        gate: "Gate";
      };
      readonlyHint: "The built-in definition is read-only. Duplicate it to edit.";
      role: {
        implementer: "Implementer";
        planner: "Planner";
        reviewer: "Reviewer";
      };
      save: "Save";
      terminal: {
        blocked: "Blocked";
        cancelled: "Cancelled";
        completed: "Completed";
        exhausted: "Exhausted";
        failed: "Failed";
      };
      toast: {
        deleteFailed: "Could not delete this workflow.";
        deleted: "Workflow deleted";
        duplicateFailed: "Could not duplicate this workflow.";
        duplicated: "Workflow duplicated";
        loadFailed: "Could not load workflows.";
        saveFailed: "Could not save this workflow.";
        saved: "Workflow saved";
      };
    };
    workspaces: {
      current: "Current";
      description: "Choose a workspace to manage its settings.";
      emptyDescription: "Add a workspace from the Work group in the sidebar, then come back to configure it.";
      emptyTitle: "No workspaces";
      environmentDescription: "Scripts and actions for worktrees Cocurdex creates for this workspace.";
      environmentTitle: "Environment";
      noResults: "No matching workspaces";
      search: "Search workspaces";
      worktreeSettings: "Worktree settings";
    };
    worktrees: {
      actionName: "Action name";
      actionNamePlaceholder: "Name, e.g. Dev server";
      actionScriptPlaceholder: "npm run dev";
      actionsDescription: 'Shown in the session "…" menu; each runs in a new terminal tab.';
      actionsTitle: "Actions";
      addAction: "Add action";
      archivedSession: "{{title}} (archived)";
      askAgent: "Ask agent";
      browse: "Browse";
      cleanupDescription: "Runs in the worktree directory before Cocurdex removes an unused checkout.";
      cleanupPlaceholder: "Optional. Example: rm -rf .turbo";
      cleanupTitle: "Cleanup script";
      delete: "Delete";
      deleteFailed: "Could not delete worktree. {{message}}";
      detached: "Detached HEAD";
      empty: "No managed worktrees yet.";
      fetchDescription: "Fetch remotes before creating a new worktree so the start point is current.";
      fetchTitle: "Always fetch upstream before creating worktrees";
      groupTitle: "Managed worktrees";
      inventoryDescription: "Checkouts Cocurdex created for sessions. Setup and cleanup scripts stay in workspace settings.";
      loading: "Loading…";
      newSession: "New session in this worktree";
      noSessions: "No sessions are using this worktree.";
      projectGroup: "Worktrees";
      refresh: "Refresh";
      removeAction: "Remove action";
      riskyPatterns: "Review carefully — contains: {{patterns}}";
      rootDescription: "Directory where Cocurdex creates managed worktrees. Leave blank to use the default location.";
      rootTitle: "Worktree root";
      save: "Save";
      saveFailed: "Could not save worktree settings. {{message}}";
      saved: "Worktree environment saved";
      setupDescription: "Runs automatically after Cocurdex creates a worktree for this workspace.";
      setupPlaceholder: "pnpm install";
      setupTitle: "Setup script";
    };
  };
}
