import {
  type AgentDescriptor,
  getAgentSessionTitleStrategy,
  getFallbackAgentPermissionModes,
  type MessageRecord,
} from "@cocurdex/shared";
import type { DesktopApi } from "./types";

const fallbackAgents: AgentDescriptor[] = [
  {
    id: "claude-agent",
    label: "Claude Agent",
    availability: "available",
    capabilities: {
      collaborationModes: ["default", "plan"],
      permissionModes: getFallbackAgentPermissionModes("claude-agent"),
      writeModes: ["read-only", "native-write"],
      supportsSteering: true,
      supportsStreaming: true,
      supportsSelections: true,
      sessionTitleStrategy: getAgentSessionTitleStrategy("claude-agent"),
      transport: "native",
    },
  },
  {
    id: "codex",
    label: "Codex",
    availability: "available",
    capabilities: {
      collaborationModes: ["default", "plan"],
      permissionModes: getFallbackAgentPermissionModes("codex"),
      writeModes: ["read-only"],
      supportsSteering: true,
      supportsStreaming: true,
      supportsSelections: true,
      sessionTitleStrategy: getAgentSessionTitleStrategy("codex"),
      transport: "native",
    },
  },
  {
    id: "grok-build",
    label: "Grok Build",
    availability: "available",
    capabilities: {
      collaborationModes: ["default", "plan"],
      permissionModes: getFallbackAgentPermissionModes("grok-build"),
      writeModes: ["native-write"],
      supportsSteering: true,
      supportsStreaming: true,
      supportsSelections: true,
      sessionTitleStrategy: getAgentSessionTitleStrategy("grok-build"),
      transport: "acp",
    },
  },
  {
    id: "opencode",
    label: "OpenCode",
    availability: "available",
    capabilities: {
      collaborationModes: ["default", "plan"],
      permissionModes: getFallbackAgentPermissionModes("opencode"),
      writeModes: ["read-only", "native-write"],
      supportsSteering: false,
      supportsStreaming: true,
      supportsSelections: true,
      sessionTitleStrategy: getAgentSessionTitleStrategy("opencode"),
      transport: "native",
    },
  },
  {
    id: "pi",
    label: "Pi",
    availability: "available",
    capabilities: {
      collaborationModes: ["default"],
      permissionModes: getFallbackAgentPermissionModes("pi"),
      writeModes: ["read-only"],
      supportsSteering: true,
      supportsStreaming: false,
      supportsSelections: true,
      sessionTitleStrategy: getAgentSessionTitleStrategy("pi"),
      transport: "native",
    },
  },
];

const fallbackApi: DesktopApi = {
  bootstrapApp: async () => ({
    workspaces: [],
    sessions: [],
    queuedAgentInputs: [],
    sessionUsage: {},
    editorViews: [],
  }),
  getHomeDir: async () => "/",
  listFontFamilies: async () => [],
  getAppUpdateState: async () => ({
    availableVersion: null,
    currentVersion: "0.0.0",
    dismissedVersion: null,
    errorMessage: null,
    releaseNotesUrl: null,
    status: "unsupported",
  }),
  checkForAppUpdate: async () => fallbackApi.getAppUpdateState(),
  dismissAppUpdate: async () => fallbackApi.getAppUpdateState(),
  installAppUpdate: async () => {},
  onAppUpdateState: () => () => {},
  getCliPathStatus: async () => ({
    available: false,
    installed: false,
    pointsToCurrentApp: false,
    binDir: "",
    installPath: "",
    sourcePath: null,
    binDirOnPath: false,
    pathHint: null,
    error: null,
  }),
  installCliOnPath: async () => fallbackApi.getCliPathStatus(),
  uninstallCliFromPath: async () => fallbackApi.getCliPathStatus(),
  getDaemonStatus: async () => ({
    running: false,
    pid: null,
    protocolVersion: null,
    runtimeFingerprint: null,
    expectedRuntimeFingerprint: null,
    socketPath: null,
    startedAt: null,
    matchesRuntime: false,
    ownedByThisApp: false,
    error: null,
  }),
  restartDaemon: async () => fallbackApi.getDaemonStatus(),
  getProductSkillsStatus: async () => ({
    scope: "global",
    packVersion: "0.0.0",
    installed: false,
    managed: false,
    installedVersion: null,
    updateAvailable: false,
    conflict: false,
    conflictSkills: [],
    skills: [],
    agentsSkillsDir: "",
    claudeSkillsDir: "",
    claudeLinkMode: "none",
    workspaceRoot: null,
    sourceAvailable: false,
    sourceRoot: "",
  }),
  installProductSkills: async () => ({
    ...(await fallbackApi.getProductSkillsStatus("global")),
    action: "skipped",
  }),
  removeProductSkills: async () => ({
    scope: "global",
    removed: false,
    agentsSkillsDir: "",
    claudeSkillsDir: "",
    removedSkills: [],
  }),
  listAgents: async () => fallbackAgents,
  listWorkspaces: async () => [],
  saveWorkspace: async () => {},
  deleteWorkspace: async () => {},
  openWorkspaceInFileManager: async () => {},
  revealPathInFileManager: async () => {},
  listWorkspaceEntries: async () => [],
  listWorkspaceFiles: async () => [],
  onWorkspaceFilesChanged: () => () => {},
  onWorkspaceGitStateChanged: () => () => {},
  listGitBranches: async () => [],
  checkoutGitBranch: async () => {},
  listGitCommits: async () => [],
  getWorkspaceGitDiff: async () => ({ status: "ok", changes: [] }),
  getWorkspaceGitStatus: async () => ({ status: "ok", entries: [] }),
  stageGitFiles: async () => {},
  unstageGitFiles: async () => {},
  discardGitFiles: async () => {},
  commitGitChanges: async () => ({
    commitHash: "",
    message: "",
    generatedMessage: false,
  }),
  generateGitCommitMessage: async () => "",
  pushGitBranch: async () => ({ branch: "", remote: "" }),
  readTextFile: async () => "",
  fileExists: async () => false,
  importDocumentAttachment: async (payload) => ({
    filePath: "",
    id: crypto.randomUUID(),
    kind: "document",
    mimeType: payload.mimeType,
    name: payload.name,
    sizeBytes: payload.sizeBytes,
  }),
  importImageAttachment: async (payload) => ({
    kind: "image",
    filePath: "",
    height: payload.height,
    id: crypto.randomUUID(),
    mimeType: payload.mimeType,
    name: payload.name,
    sizeBytes: payload.sizeBytes,
    width: payload.width,
  }),
  readImageAttachmentDataUrl: async () => "",
  readPdfData: async () => "",
  loadPdfAnnotations: async () => ({ bookmarks: [], highlights: [] }),
  savePdfAnnotations: async () => {},
  createSession: async (payload) => payload.session,
  updateSessionTitle: async () => null,
  archiveSession: async () => null,
  deleteSession: async () => {},
  refineSessionTitle: async () => null,
  listProviderConfigs: async () => [],
  listProviderTemplates: async () => [],
  readMcpConfig: async () => ({
    content: '{\n  "mcpServers": {}\n}\n',
    path: "",
  }),
  saveMcpConfig: async (content) => ({ content, path: "" }),
  saveProviderConfig: async (config) => config,
  deleteProviderConfig: async () => {},
  setProviderApiKey: async () => {},
  clearProviderApiKey: async () => {},
  listProviderModels: async () => ({ models: [], error: null }),
  listAllProviderModels: async () => [],
  saveProviderModel: async (model) => model,
  deleteProviderModel: async () => {},
  listCompatibleProvidersForAgent: async () => [],
  listAgentProviderDefaults: async () => [],
  getAgentProviderDefault: async () => null,
  setAgentProviderDefault: async () => {},
  getTitleModel: async () => null,
  setTitleModel: async () => {},
  probeTitleModel: async () => ({
    ok: false,
    latencyMs: 0,
    error: "Title model probe is unavailable outside the desktop app",
  }),
  getCommitMessageModel: async () => null,
  setCommitMessageModel: async () => {},
  getNetworkProxySettings: async () => ({
    mode: "system" as const,
    httpProxy: "",
    httpsProxy: "",
    allProxy: "",
    noProxy: "localhost,127.0.0.1,::1,.local",
  }),
  setNetworkProxySettings: async (settings) => settings,
  testNetworkProxy: async (_settings) => ({
    ok: false as const,
    durationMs: 0,
    error: "Proxy test is unavailable outside the desktop app",
  }),
  testCurrentNetworkProxy: async () => ({
    ok: false as const,
    durationMs: 0,
    error: "Proxy test is unavailable outside the desktop app",
  }),
  readCodexAccount: async () => ({
    method: null,
    email: null,
    planType: null,
    requiresOpenaiAuth: false,
  }),
  startCodexLogin: async () => {
    throw new Error("Codex login is unavailable outside the desktop app");
  },
  waitCodexLogin: async () => ({ success: false, error: null }),
  cancelCodexLogin: async () => {},
  logoutCodex: async () => {},
  listSessionMessages: async () => ({
    messages: [],
    turnStats: {},
    turnChangeSets: {},
  }),
  listSessionToolCalls: async () => [],
  getToolCallResult: async () => null,
  undoTurnChanges: async () => ({
    changeSetId: "",
    status: "failed" as const,
    files: [],
    recoveryCheckpointRef: null,
  }),
  getTurnChangeFile: async (payload) => ({
    path: payload.path,
    side: payload.side,
    reviewKind: "text",
    exists: false,
    sizeBytes: null,
    hash: null,
    text: null,
    contentBase64: null,
    mimeType: null,
  }),
  sendMessage: async (payload) =>
    ({
      id: crypto.randomUUID(),
      sessionId: payload.session.id,
      role: "user",
      content: payload.content,
      attachments: payload.attachments ?? [],
      createdAt: new Date().toISOString(),
    }) satisfies MessageRecord,
  updateQueuedInput: async (payload) =>
    ({
      id: payload.messageId,
      sessionId: payload.sessionId,
      role: "user",
      content: payload.content,
      attachments: [],
      createdAt: new Date().toISOString(),
    }) satisfies MessageRecord,
  deleteQueuedInput: async () => {},
  steerQueuedInput: async (payload) =>
    ({
      id: payload.messageId,
      sessionId: payload.sessionId,
      role: "user",
      content: "",
      attachments: [],
      createdAt: new Date().toISOString(),
    }) satisfies MessageRecord,
  submitPreviousMessage: async (payload) =>
    ({
      id: payload.messageId,
      sessionId: payload.session.id,
      role: "user",
      content: payload.content,
      attachments: payload.attachments ?? [],
      createdAt: new Date().toISOString(),
    }) satisfies MessageRecord,
  getPreviousMessageCheckpointStatus: async () => ({ available: false }),
  saveEditorView: async () => {},
  stopSession: async () => {},
  listSlashCommands: async () => [],
  setSessionRuntimeMode: async () => {},
  setSessionRuntimeConfig: async () => [],
  resolvePermission: async () => {},
  resolveQuestion: async () => {},
  resolvePlanApproval: async () => {},
  onAgentEvent: () => () => {},
  openWorkspace: async () => ({ canceled: true, filePaths: [] }),
  consumePendingOpenFolder: async () => null,
  getPathForFile: () => null,
  resolveWorkspaceOpenPath: async () => null,
  onOpenWorkspaceFromCli: () => () => {},
  setWindowSurfaceColor: async () => {},
  browserNavigate: async () => {},
  browserReload: async () => {},
  browserStop: async () => {},
  browserGoBack: async () => {},
  browserGoForward: async () => {},
  browserToggleAnnotationMode: async () => {},
  browserCaptureScreenshot: async () => "",
  onBrowserAnnotation: () => () => {},
  onBrowserLoading: () => () => {},
  onBrowserTitle: () => () => {},
  onBrowserNavigated: () => () => {},
  onBrowserError: () => () => {},
  setBrowserBounds: async () => {},
  browserShow: async () => {},
  logRendererError: async () => {},
  exportDiagnostics: async () => ({ fileCount: 0, outputPath: "" }),
  openExternal: async () => {},
  ptySpawn: async (payload) => ({
    terminalId: payload.terminalId,
    workspaceId: payload.workspaceId,
    pid: 0,
    shell: "/bin/zsh",
    cwd: payload.cwd,
  }),
  ptyWrite: async () => {},
  ptyResize: async () => {},
  ptyKill: async () => {},
  onPtyData: () => () => {},
  onPtyExit: () => () => {},
  onPtyActivity: () => () => {},
  startWorkspaceSearch: async () => {},
  cancelWorkspaceSearch: async () => {},
  onWorkspaceSearchResult: () => () => {},
  onWorkspaceSearchDone: () => () => {},
  onWorkspaceSearchError: () => () => {},
  // Pure chat fallbacks — used in unit tests / SSR contexts where the
  // electron preload bridge isn't present.
  chatList: async () => [],
  chatGet: async () => null,
  chatCreate: async (payload) => ({
    id: crypto.randomUUID(),
    title: payload.title ?? "New chat",
    providerId: payload.providerId,
    modelId: payload.modelId,
    systemPrompt: payload.systemPrompt ?? null,
    presetId: payload.presetId ?? null,
    webSearchEnabled: payload.webSearchEnabled ?? false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessageAt: null,
    archivedAt: null,
  }),
  chatUpdate: async () => null,
  chatArchive: async () => null,
  chatDelete: async () => {},
  chatSendMessage: async (payload) => ({
    id: crypto.randomUUID(),
    conversationId: payload.conversationId,
    role: "user",
    content: [{ type: "text", text: payload.text }],
    status: "completed",
    usage: null,
    sources: [],
    error: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }),
  chatRetryMessage: async () => null,
  chatEditMessage: async (payload) => ({
    id: payload.messageId,
    conversationId: payload.conversationId,
    role: "user",
    content: [{ type: "text", text: payload.text }],
    status: "completed",
    usage: null,
    sources: [],
    error: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }),
  chatStopStream: async () => {},
  onChatEvent: () => () => {},
  // Data fallbacks used in unit tests and SSR without the preload bridge.
  notesList: async () => [],
  notesGet: async () => null,
  notesCreate: async (payload) => {
    const kind = payload.kind ?? "note";
    const now = new Date().toISOString();
    return {
      id: crypto.randomUUID(),
      parentId: payload.parentId ?? null,
      workspaceId: payload.workspaceId ?? null,
      kind,
      title: payload.title ?? "",
      icon: payload.icon ?? null,
      sortOrder: 0,
      revision: 1,
      createdAt: now,
      updatedAt: now,
      bodyMarkdown: "",
    };
  },
  notesUpdate: async (payload) => {
    const now = new Date().toISOString();
    return {
      id: payload.id,
      parentId: null,
      workspaceId: payload.workspaceId ?? null,
      kind: "note" as const,
      title: payload.title ?? "",
      icon: payload.icon ?? null,
      sortOrder: 0,
      revision: (payload.expectedRevision ?? 0) + 1,
      createdAt: now,
      updatedAt: now,
      bodyMarkdown: payload.bodyMarkdown ?? "",
    };
  },
  notesRename: async (payload) => {
    const now = new Date().toISOString();
    return {
      id: payload.id,
      parentId: null,
      workspaceId: null,
      kind: "note" as const,
      title: payload.title,
      icon: null,
      sortOrder: 0,
      revision: (payload.expectedRevision ?? 0) + 1,
      createdAt: now,
      updatedAt: now,
      bodyMarkdown: "",
    };
  },
  notesMove: async (payload) => {
    const now = new Date().toISOString();
    return {
      id: payload.id,
      parentId: payload.parentId,
      workspaceId: null,
      kind: "note" as const,
      title: payload.id,
      icon: null,
      sortOrder: payload.sortOrder ?? 0,
      revision: (payload.expectedRevision ?? 0) + 1,
      createdAt: now,
      updatedAt: now,
      bodyMarkdown: "",
    };
  },
  notesDelete: async () => {},
  // Issues fallbacks (shared issues + multi-issue views)
  issueListViews: async () => [],
  issueLoad: async () => null,
  issueGet: async (payload) => {
    const now = new Date().toISOString();
    return {
      id: payload.id,
      columnId: "backlog",
      viewId: payload.viewId ?? "project",
      title: "",
      description: null,
      color: null,
      status: "backlog",
      priority: "none",
      workspaceId: null,
      sortOrder: 0,
      revision: 1,
      createdAt: now,
      updatedAt: now,
    };
  },
  issueCreateView: async (payload) => ({
    id: "view",
    title: payload.title ?? "New view",
    icon: payload.icon ?? null,
    groupBy: "status" as const,
    layout: "board" as const,
    filters: [],
    revision: 1,
  }),
  issueDeleteView: async () => {},
  issueUpdateView: async (payload) => {
    const now = new Date().toISOString();
    return {
      view: {
        id: payload.viewId,
        title: payload.title ?? "Project view",
        icon: payload.icon ?? null,
        groupBy: payload.groupBy ?? "status",
        layout: payload.layout ?? "board",
        filters: payload.filters ?? [],
        revision: (payload.expectedRevision ?? 0) + 1,
        createdAt: now,
        updatedAt: now,
      },
      columns: [],
      statusOptions: [],
      priorityOptions: [],
      issues: [],
    };
  },
  issueCreateColumn: async (payload) => {
    const now = new Date().toISOString();
    return {
      id: "column",
      viewId: payload.viewId,
      title: payload.title ?? "",
      color: payload.color ?? null,
      sortOrder: payload.sortOrder ?? 0,
      createdAt: now,
      updatedAt: now,
    };
  },
  issueUpdateColumn: async (payload) => {
    const now = new Date().toISOString();
    return {
      id: payload.id,
      viewId: payload.viewId,
      title: payload.title ?? "",
      color: payload.color ?? null,
      sortOrder: 0,
      createdAt: now,
      updatedAt: now,
    };
  },
  issueMoveColumn: async (payload) => {
    const now = new Date().toISOString();
    return {
      id: payload.id,
      viewId: payload.viewId,
      title: "",
      color: null,
      sortOrder: payload.sortOrder,
      createdAt: now,
      updatedAt: now,
    };
  },
  issueDeleteColumn: async () => {},
  issueCreate: async (payload) => {
    const now = new Date().toISOString();
    return {
      id: "001",
      columnId: payload.columnId,
      viewId: payload.viewId,
      title: payload.title ?? "",
      description: payload.description ?? null,
      color: payload.color ?? null,
      status: payload.status ?? payload.columnId,
      priority: payload.priority ?? "none",
      workspaceId: payload.workspaceId ?? null,
      sortOrder: payload.sortOrder ?? 0,
      revision: 1,
      createdAt: now,
      updatedAt: now,
    };
  },
  issueUpdate: async (payload) => {
    const now = new Date().toISOString();
    return {
      id: payload.id,
      columnId: "backlog",
      viewId: payload.viewId,
      title: payload.title ?? "",
      description: payload.description ?? null,
      color: payload.color ?? null,
      status: payload.status ?? "backlog",
      priority: payload.priority ?? "none",
      workspaceId: payload.workspaceId ?? null,
      sortOrder: 0,
      revision: (payload.expectedRevision ?? 0) + 1,
      createdAt: now,
      updatedAt: now,
    };
  },
  issueMove: async (payload) => {
    const now = new Date().toISOString();
    return {
      id: payload.id,
      columnId: payload.columnId,
      viewId: payload.viewId,
      title: "",
      description: null,
      color: null,
      status: payload.columnId,
      priority: "none",
      workspaceId: null,
      sortOrder: payload.sortOrder,
      revision: (payload.expectedRevision ?? 0) + 1,
      createdAt: now,
      updatedAt: now,
    };
  },
  issueDelete: async () => {},
  searchDocuments: async () => [],
  onDataChanged: () => () => {},
};

function getDesktopApi(): DesktopApi {
  if (typeof window === "undefined") {
    return fallbackApi;
  }

  return window.desktopApi ?? fallbackApi;
}

export const desktopApi = new Proxy(fallbackApi, {
  get(_target, property, receiver) {
    const api = getDesktopApi();
    return Reflect.get(api, property, receiver);
  },
}) satisfies DesktopApi;
