import { describe, expect, it } from "vitest";
import { createSchemaSql } from "./schema";

describe("createSchemaSql", () => {
  it("creates the complete Cocurdex application schema", () => {
    const sql = createSchemaSql();

    expect(sql).toContain("CREATE TABLE IF NOT EXISTS workspaces");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS sessions");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS session_attention");
    expect(sql).toContain("collaboration_mode TEXT NOT NULL DEFAULT 'default'");
    expect(sql).toContain("permission_mode TEXT");
    expect(sql).toContain("session_kind TEXT NOT NULL DEFAULT 'main'");
    expect(sql).toContain("parent_session_id TEXT");
    expect(sql).toContain("parent_tool_call_id TEXT");
    expect(sql).toContain("archived_at TEXT");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS messages");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS queued_agent_inputs");
    expect(sql).toContain("kind TEXT");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS tool_calls");
    expect(sql).toContain("raw_input_json TEXT");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS session_usage");
    expect(sql).toContain("usage_json TEXT NOT NULL");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS message_turn_stats");
    expect(sql).toContain("duration_ms INTEGER NOT NULL");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS turn_change_sets");
    expect(sql).toContain("host_before_checkpoint_ref TEXT");
    expect(sql).toContain("host_before_checkpoint_kind TEXT");
    expect(sql).toContain("host_recovery_checkpoint_ref TEXT");
    expect(sql).toContain("outcome TEXT");
    expect(sql).toContain("native_files_json TEXT");
    expect(sql).toContain("undoable INTEGER");
    expect(sql).toContain("idx_turn_change_sets_session");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS editor_views");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS agent_provider_sessions");
    expect(sql).toContain("api TEXT");
    expect(sql).toContain("compat_json TEXT");
    expect(sql).toContain("capabilities_json TEXT");
    expect(sql).toContain("thinking_level_map_json TEXT");
    expect(sql).toContain("idx_messages_session_created");
    expect(sql).toContain("idx_tool_calls_session_started");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS notes");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS issues");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS issue_views");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS issue_view_columns");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS tags");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS note_tags");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS note_links");
    expect(sql).toContain("CREATE VIRTUAL TABLE IF NOT EXISTS note_fts");
    expect(sql).toContain("CREATE VIRTUAL TABLE IF NOT EXISTS issue_fts");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS workflow_runs");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS workflow_step_runs");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS workflow_attempts");
    expect(sql).toContain("runtime_identity_json TEXT NOT NULL");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS workflow_artifacts");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS workflow_gate_decisions");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS workflow_suspensions");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS workflow_actions");
    expect(sql).not.toContain("CREATE TABLE IF NOT EXISTS orchestration_runs");
    expect(sql).not.toContain("CREATE TABLE IF NOT EXISTS agent_task_runs");
    expect(sql).not.toContain("CREATE TABLE IF NOT EXISTS task_event_log");
  });
});
